Case insensitive compare 1075
ClibMouse/ClickHouse pull request #159
Opened 2022-12-11 22:43 UTC by SadiHassan

### Changelog category (leave one):
- New Feature
- Improvement
- Bug Fix (user-visible misbehavior in official stable or prestable release)
- Performance Improvement
- Backward Incompatible Change
- Build/Testing/Packaging Improvement
- Documentation (changelog entry is not required)
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

2023-01-18 14:20 UTC, ltrk2 requested changes

2023-01-18 14:20 UTC, ltrk2 commented on src/Parsers/Kusto/ParserKQLOperators.cpp
> +String KQLOperators::genInOpExprCis(std::vector<String> &tokens, IParser::Pos &token_pos, String kql_op, String ch_op)
In here you use `toString` wrappings just like you do in `genEqOpExprCis`. Isn't it unnecessary, since all the parameters are supposed to be strings?

2023-01-18 14:20 UTC, ltrk2 commented on src/Parsers/Kusto/ParserKQLOperators.cpp
> +        new_expr = new_expr + ch_op + " kql";
```suggestion
        new_expr += ch_op + " kql";
```

2023-01-23 21:41 UTC, SadiHassan commented on src/Parsers/Kusto/ParserKQLOperators.cpp
> +        tokens.pop_back();
Updated, thanks!

2023-01-23 21:41 UTC, SadiHassan commented on src/Parsers/Kusto/ParserKQLOperators.cpp
> +        new_expr += tmp_arg;
Updated, thanks!

2023-01-23 21:41 UTC, SadiHassan commented on src/Parsers/Kusto/ParserKQLOperators.cpp
> +    String tmp_arg = String(token_pos->begin, token_pos->end);
Updated, thanks!

2023-01-23 21:41 UTC, SadiHassan commented on src/Parsers/Kusto/ParserKQLOperators.cpp
> +    for(auto s : tokens)
Updated, thanks!

2023-01-23 21:41 UTC, SadiHassan commented on src/Parsers/Kusto/ParserKQLOperators.cpp
> +String KQLOperators::genEqOpExprCis(std::vector<String> &tokens, IParser::Pos &token_pos, String ch_op)
Updated, thanks!

2023-01-23 21:41 UTC, SadiHassan commented on src/Parsers/Kusto/ParserKQLOperators.cpp
> +String KQLOperators::genInOpExprCis(std::vector<String> &tokens, IParser::Pos &token_pos, String kql_op, String ch_op)
Updated, thanks!

2023-01-23 21:41 UTC, SadiHassan commented on src/Parsers/Kusto/ParserKQLOperators.cpp
> +String KQLOperators::genInOpExprCis(std::vector<String> &tokens, IParser::Pos &token_pos, String kql_op, String ch_op)
Updated, thanks!

2023-01-23 21:42 UTC, SadiHassan commented on src/Parsers/Kusto/ParserKQLOperators.cpp
> +        new_expr = new_expr + ch_op + " kql";
Updated, thanks!

2023-01-23 22:26 UTC, ltrk2 approved these changes

2023-01-24 01:15 UTC, merged