implementation of has_ipv4, has_any_ipv4, has_ipv4_prefix, and has_an…
ClibMouse/ClickHouse pull request #214
Opened 2023-02-08 14:26 UTC by bemitc

### Changelog category (leave one):
- New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Added Kusto functions has_ipv4(), has_any_ipv4(), has_ipv4_prefix(), and has_any_ipv4_prefix()

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

2023-02-08 22:48 UTC, kashwy reviewed
1. Add unit test

2. Use `02366_kql` as the prefix for functional test files like other KQL functional test:
   02366_kql_func_dynamic.sql

3. Use  KQL statement in functional test.

2023-02-08 22:59 UTC, kashwy commented on src/Functions/Kusto/kqlHasAnyIpv4.cpp
> +        auto argsLength = arguments.size();
follow the style of variable name:
https://clickhouse.com/docs/en/development/style#names

2023-02-08 23:00 UTC, kashwy commented on src/Functions/Kusto/kqlHasAnyIpv4.cpp
> +        auto bool_type = std::make_shared<DataTypeUInt8>();
variable names

2023-02-08 23:01 UTC, kashwy commented on src/Functions/Kusto/kqlHasAnyIpv4.cpp
> +        std::vector<std::string> ipList;
https://clickhouse.com/docs/en/development/style#names
argsLength  , ipList

2023-02-08 23:01 UTC, kashwy commented on src/Functions/Kusto/kqlHasAnyIpv4Prefix.cpp
> +        auto argsLength = arguments.size();
variable name

2023-02-08 23:04 UTC, kashwy commented on src/Parsers/Kusto/KustoFunctions/KQLIPFunctions.cpp
> +{
can this use direct mapping?

2023-02-08 23:05 UTC, kashwy commented on src/Parsers/Kusto/KustoFunctions/KQLIPFunctions.cpp
> +{
can this use direct mapping?

2023-02-08 23:31 UTC, bemitc commented on src/Functions/Kusto/kqlHasAnyIpv4.cpp
> +        auto argsLength = arguments.size();
I've removed the camelcase variable names

2023-02-08 23:52 UTC, bemitc commented on src/Parsers/Kusto/KustoFunctions/KQLIPFunctions.cpp
> +{
Yes. I've updated the non any functions to use direct mapping instead (which I was previously unaware of).

2023-02-09 00:34 UTC, ltrk2 commented
@bemitc in general, I think you could have more interesting functional tests. Feel free to experiment with edge cases (eg. empty strings, near-miss cases like '127.0.0.1111' or '127.0.0.a') and try to break your own implementation as much as you can. For starters, you could always include any test cases that the KQL specification of a given function contains.

I think you could also use just a single functional test case file, since the functions you are implementing are very much related and could benefit from the same test data. If you'd prefer to split it into multiple files though, that's also fine, just make sure to use the `02366_kql` prefix as @kashwy also mentioned.

2023-02-09 00:35 UTC, ltrk2 commented on tests/queries/0_stateless/02522_has_ipv4.sql
> +INSERT INTO has_ipv4_tbl (ip) VALUES ('127.0.0.1');
You could perform these in a single query. The same goes for the other functional test files as well.

2023-02-09 00:38 UTC, ltrk2 commented on tests/queries/0_stateless/02523_has_any_ipv4.sql
> +SELECT kql_has_any_ipv4('XXX 192.168.0.255', '192.168.0.255', '192.168.0.256');
I think you could have the test data setup in the beginning and put the teardown at the very end and only have actual tests in between.

2023-02-09 00:39 UTC, bemitc commented on tests/queries/0_stateless/02522_has_ipv4.sql
> +INSERT INTO has_ipv4_tbl (ip) VALUES ('127.0.0.1');
I had some problems with tests that throw exceptions. However, I see now you can add special formatted comments which indicate expected error codes which probably will help out. I'll take another pass on a better set of functional tests before I start working on unit tests.

2023-02-09 00:45 UTC, ltrk2 commented on src/Parsers/Kusto/KustoFunctions/KQLIPFunctions.cpp
> +    return true;
I believe that you could mold the native function in a way that this preprocessing would no longer be necessary. Was there a particular reason that you chose this route?

2023-02-09 00:57 UTC, bemitc commented on src/Parsers/Kusto/KustoFunctions/KQLIPFunctions.cpp
> +    return true;
I missed the directMaping call when implementing convertImpl. It looks like I can directMap even variadic functions and let getReturnTypeImpl take care of enforcing the number of arguments (which it already does). I'll make that change.

2023-02-09 01:32 UTC, ltrk2 requested changes

2023-02-09 02:16 UTC, ltrk2 requested changes
Please make similar changes to `FunctionKqlHasIpv4PrefixGeneric` than you will to `FunctionKqlHasIpv4Generic` once you go through all of my comments.

2023-02-09 02:16 UTC, ltrk2 commented on src/Functions/Kusto/kqlHasAnyIpv4.cpp
> +                    ips.push_back(ip);
```suggestion
                    auto ip = arguments[i].column->getDataAt(0).toString();
                    ips.push_back(std::move(ip));
```

2023-02-09 02:16 UTC, ltrk2 commented on src/Functions/Kusto/kqlHasAnyIpv4.cpp
> +            size_t len0 = array0.get<Array>().size();
```suggestion
            const auto len0 = array0.get<Array>().size();
```

2023-02-09 02:16 UTC, ltrk2 commented on src/Functions/Kusto/kqlHasAnyIpv4.cpp
> +            std::string source = arguments[0].column->getDataAt(0).toString();
You're treating argument #0 as if it could only ever be a literal. You need to perform this part for every row in the column and produce a result into a column of type `ColumnUInt8`.

Example, that works in ADX:
```
datatable (str:string) [
    'adsddsd a 127.0.0.1 u bn 192.168.0.1 aaa',
    'uuuuuu 255.255.255.255 weqee'
] | extend has_any_ipv4(str, '127.0.0.1');
```

In order to complicate things further, argument #1 can also be a column in case of `has_ipv4` as per ADX:
```
datatable (str:string, ip:string) [
    'adsddsd a 127.0.0.1 u bn 192.168.0.1 aaa', '127.0.0.1',
    'uuuuuu 255.255.255.255 weqee', '0.0.0.0'
] | extend has_ipv4(str, ip);
```

So you'll need a find a way to handle all of these.

2023-02-09 02:16 UTC, ltrk2 commented on src/Functions/Kusto/kqlHasAnyIpv4.cpp
> +                    if (std::any_of(ips.begin(), ips.end(), [i, matches](const std::string & str) -> bool { return str == matches[i]; }))
It seems to me that `found_match` is unnecessary, since you can simply conclude any business once you find a match.

2023-02-09 04:09 UTC, bemitc commented on src/Functions/Kusto/kqlHasAnyIpv4.cpp
> +            std::string source = arguments[0].column->getDataAt(0).toString();
Hmm, i'll look into this, but in my testing I always seemed to be called one row at a time (with the first call when invoked from a table providing 0 rows).

![image](https://user-images.githubusercontent.com/12734365/217715566-e61b1285-3730-4835-acf4-16e61de06dfa.png)

2023-02-09 14:36 UTC, ltrk2 commented on src/Functions/Kusto/kqlHasAnyIpv4.cpp
> +            std::string source = arguments[0].column->getDataAt(0).toString();
It seems to me that it's a special case you've encountered: functions are executed on every part a table consists of. In your case, this happens because you're creating one row per part by performing inserts as separate queries. The same is true for every functional test you've written, so based on this it might seem that everything is fine. However, it isn't.

Consider the following example:
```
drop table if exists test;
create table test (str String, ip String) engine = Memory;
insert into test values ('adsddsd a 127.0.0.1 u bn 192.168.0.1 aaa', '127.0.0.1'), ('uuuuuu 255.255.255.255 weqee', '0.0.0.0');

test | extend has_ipv4(str, ip);
```

Result on your feature branch, since you're only considering the first row of any column:
```
┌─str──────────────────────────────────────┬─ip────────┬─Column1─┐
│ adsddsd a 127.0.0.1 u bn 192.168.0.1 aaa │ 127.0.0.1 │       1 │
│ uuuuuu 255.255.255.255 weqee             │ 0.0.0.0   │       1 │
└──────────────────────────────────────────┴───────────┴─────────┘
```

2023-02-13 03:53 UTC, kashwy commented on src/Functions/Kusto/kqlHasAnyIpv4.cpp
> +        const auto max_rows = std::max_element(arguments.begin(), arguments.end(), [] (ColumnWithTypeAndName const & lhs, ColumnWithTypeAndName const & rhs) { return lhs.column->size() < rhs.column->
why need this? there is already a` input_rows_count`

2023-02-13 04:29 UTC, bemitc commented on src/Functions/Kusto/kqlHasAnyIpv4.cpp
> +        const auto max_rows = std::max_element(arguments.begin(), arguments.end(), [] (ColumnWithTypeAndName const & lhs, ColumnWithTypeAndName const & rhs) { return lhs.column->size() < rhs.column->
Laszlo told me it was either 0 for a constant expression and 1 when it's a column, but that appears to perhaps no longer be the case. I'll remove this and make use of input_rows_count.

2023-02-15 20:25 UTC, ltrk2 commented on src/Functions/Kusto/kqlHasAnyIpv4.cpp
> +        const auto max_rows = std::max_element(arguments.begin(), arguments.end(), [] (ColumnWithTypeAndName const & lhs, ColumnWithTypeAndName const & rhs) { return lhs.column->size() < rhs.column->
I still consider the issue Brian mentioned in his comment relevant. Please create functional tests that insert data in bulk in order to make sure that everything runs fine.

2023-02-15 20:47 UTC, kashwy commented on src/Functions/Kusto/kqlHasAnyIpv4.cpp
> +        const auto max_rows = std::max_element(arguments.begin(), arguments.end(), [] (ColumnWithTypeAndName const & lhs, ColumnWithTypeAndName const & rhs) { return lhs.column->size() < rhs.column->
input_rows_count is the one you need to handle the rows.

it can be 0, 1 or more than 1 , depends how the data is read  I think.

there are multiple threads to read data, so each thread can have 0 ,1 or more rows ,  this is passed to function as input_rows_count , and all args have the same rows, the previous code to get max size of args is not necessary.

to process the rows, iterate the rows from 0 to  input_rows_count is ok like:

```
for (size_t  i  = 0;  i < input_rows_count ; ++i )
{
  process each row
}
```

2023-02-15 23:24 UTC, ltrk2 commented on src/Functions/Kusto/kqlHasAnyIpv4.cpp
> +        const auto max_rows = std::max_element(arguments.begin(), arguments.end(), [] (ColumnWithTypeAndName const & lhs, ColumnWithTypeAndName const & rhs) { return lhs.column->size() < rhs.column->
Hmm.. I see. Okay, sounds good to me!

2023-02-15 23:43 UTC, bemitc commented on src/Functions/Kusto/kqlHasAnyIpv4.cpp
> +        const auto max_rows = std::max_element(arguments.begin(), arguments.end(), [] (ColumnWithTypeAndName const & lhs, ColumnWithTypeAndName const & rhs) { return lhs.column->size() < rhs.column->
Sunday I did verify that input_rows_count contained the number of rows included in my insert (and stopped inserting 1 row at a time) before I made the change switching to input_rows_count instead of getting the maximum row count across all arguments. When I inserted 3 rows, input_rows_count was 3.

2023-02-17 14:50 UTC, kashwy commented on src/Functions/Kusto/kqlHasAnyIpv4.cpp
> +                    auto arg = arguments[j].column->size() == input_rows_count ? arguments[j].column->getDataAt(i).toString() : arguments[j].column->getDataAt(0).toString();
I don't understand why checking  `arguments[j].column->size() == input_rows_count`

2023-02-17 16:00 UTC, bemitc commented on src/Functions/Kusto/kqlHasAnyIpv4.cpp
> +                    auto arg = arguments[j].column->size() == input_rows_count ? arguments[j].column->getDataAt(i).toString() : arguments[j].column->getDataAt(0).toString();
I'll change that. I had thought that a literal would have a size() of 1, but it looks like it's duplicated to match input_rows_count.

2023-02-22 23:43 UTC, ltrk2 requested changes

2023-02-22 23:43 UTC, ltrk2 commented on tests/queries/0_stateless/02366_kql_func_has_any_ipv4.sql
> +IP_ARRAY | extend has_any_ipv4_prefix(haystack, dynamic(needle));
You could have some kind of separation here to make it easier on someone trying to make a connection between the query and its reference output. For example: `print -- #1 --;` before each query with its unique ordinal.

2023-02-22 23:43 UTC, ltrk2 commented on src/Functions/Kusto/kqlHasAnyIpv4.cpp
> +        auto isipv4string = [&, result_type] (ColumnsWithTypeAndName args) { return FunctionFactory::instance().get("isIPv4String", context)->build(args)->execute(args, result_type, 1); };
```suggestion
        const auto is_ipv4_string = [&, result_type] (ColumnsWithTypeAndName args) { return FunctionFactory::instance().get("isIPv4String", context)->build(args)->execute(args, result_type, 1); };
```

2023-02-22 23:43 UTC, ltrk2 commented on src/Functions/Kusto/kqlHasAnyIpv4.cpp
> +                    auto isipv4 = isipv4string(isipv4string_args);
```suggestion
                    const auto is_ipv4 = isipv4string(isipv4string_args);
```

2023-02-22 23:43 UTC, ltrk2 commented on src/Functions/Kusto/kqlHasAnyIpv4.cpp
> +                    const ColumnsWithTypeAndName isipv4string_args = {ColumnWithTypeAndName(column_ip, std::make_shared<DataTypeString>(), "ip")};
```suggestion
                    const ColumnsWithTypeAndName is_ipv4_string_args = {ColumnWithTypeAndName(column_ip, std::make_shared<DataTypeString>(), "ip")};
```

2023-02-22 23:43 UTC, ltrk2 commented on src/Functions/Kusto/kqlHasAnyIpv4.cpp
> +template <typename Name, bool is_any>
Instead of the `is_any` parameter of type `bool` you could have something more descriptive, such as an `enum` (eg. `ArgumentPolicy` with choices like `Single` or `Variadic` or anything even more descriptive you can think of) that clearly explains the choice.

2023-02-22 23:43 UTC, ltrk2 commented on src/Functions/Kusto/kqlHasAnyIpv4.cpp
> +            }
I think you could extract this into a separate function local to the translation unit, because its purpose is quite clear: to retrieve valid IP addresses from any arguments there may be.

2023-02-22 23:43 UTC, ltrk2 commented on src/Functions/Kusto/kqlHasAnyIpv4.cpp
> +                for (size_t j = 1; j < args_length; j++)
If you wanted to make this part more elegant you could use [`std::ranges::copy_if`](https://en.cppreference.com/w/cpp/algorithm/ranges/copy) on the arguments with the first element dropped and the range transformed using `std::views::transform` with a lambda equivalent of `arguments[j].column->getDataAt(i).toString()` as the transform function. The predicate would essentially be the same as the inside of this scope, save for the `push_back`.

This comment also goes for the part where you do similar things to an array.

2023-02-22 23:43 UTC, ltrk2 commented on src/Functions/Kusto/kqlHasAnyIpv4.cpp
> +                        if (std::any_of(ips.begin(), ips.end(), [j, matches](const std::string & str) -> bool { return str == matches[j]; }))
This should be a `find_if`, if I'm not mistaken. If so, you can use `std::ranges::find_if`.

2023-02-22 23:43 UTC, ltrk2 commented on src/Functions/Kusto/kqlHasAnyIpv4.cpp
> +                    for (size_t j = 0; j < matches.size(); j++)
You could have `std::ranges::any_of` instead of this loop with a break and the `bool res`.

2023-02-22 23:43 UTC, ltrk2 commented on src/Functions/Kusto/kqlHasAnyIpv4.cpp
> +            result_column->insertValue(UInt8(res));
In order to achieve something more performant at little cost in complexity you can save on virtual function calls by retrieving the underlying container using `ColumnUInt8::getData` and modifying that directly.

2023-02-22 23:43 UTC, ltrk2 commented on src/Functions/Kusto/kqlHasAnyIpv4Prefix.cpp
> +        return std::make_shared<DataTypeUInt8>();
This looks very similar to `FunctionKqlHasIpv4Generic`. If it's the same, you can just create a common header file and eliminate any duplication.

2023-02-22 23:43 UTC, ltrk2 commented on src/Functions/Kusto/kqlHasAnyIpv4Prefix.cpp
> +class FunctionKqlHasIpv4PrefixGeneric : public IFunction
Please try to apply my comments for `FunctionKqlHasIpv4Generic` to this one as well, because there's great similarity.

2023-02-26 06:26 UTC, kashwy commented on src/Functions/Kusto/kqlHasAnyIpv4.cpp
> +        {
use `++i` instead of `i++`
https://clickhouse.com/docs/en/development/style
32. Always use the prefix increment/decrement operators if postfix is not required.

2023-02-27 14:50 UTC, kashwy commented
@ltrk2 can you verify ? if all good , please re-base and merge. thanks

2023-02-27 15:09 UTC, ltrk2 commented
@kashwy sure, I'll take a look and discuss any remaining items with @bemitc.

2023-03-01 12:54 UTC, ltrk2 approved these changes

2023-03-02 17:41 UTC, merged