bug_fix_2159
ClibMouse/ClickHouse pull request #216
Opened 2023-02-12 03:16 UTC by SadiHassan

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

2023-02-13 15:03 UTC, ltrk2 requested changes

2023-02-13 15:03 UTC, ltrk2 commented on src/Parsers/Kusto/KustoFunctions/IParserKQLFunction.cpp
> +            output += '\'';
```suggestion
            output += ch;
```

2023-02-16 13:12 UTC, SadiHassan commented
@kashwy PR is rebased and tested.

2023-02-16 14:31 UTC, kashwy approved these changes

2023-02-16 20:25 UTC, ltrk2 commented
@SadiHassan please don't forget about the rest of the review comments.

2023-02-23 23:13 UTC, SadiHassan commented on src/Parsers/Kusto/KustoFunctions/IParserKQLFunction.cpp
> +    for (auto & ch: input)
Changes are applied. Thank you!

2023-02-23 23:13 UTC, SadiHassan commented on src/Parsers/Kusto/KustoFunctions/IParserKQLFunction.cpp
> +            output += '\'';
Changes are applied. Thank you!

2023-02-23 23:17 UTC, merged