Kusto phase2 summarize - Issue #731
ClibMouse/ClickHouse pull request #22
Opened 2022-07-27 12:03 UTC by SadiHassan

### Changelog category (leave one):
- New Feature
- Improvement
- Bug Fix (user-visible misbehavior in official stable or prestable release)
- Performance Improvement
- Backward Incompatible Change
- Build/Testing/Packaging Improvement
- Documentation (changelog entry is not required)
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

2022-07-27 13:19 UTC, kashwy commented on src/Parsers/Kusto/KustoFunctions/KQLAggregationFunctions.cpp
> +        out = "groupArrayIf(" + max_size + " , " + expr + " , " + predicate+ " )";
this is not a correct syntax

2022-07-27 13:20 UTC, kashwy commented on src/Parsers/Kusto/KustoFunctions/KQLAggregationFunctions.cpp
> +        out = "groupUniqArrayIf(" + max_size + " , " + expr + " , " + predicate+ " )";
this is not a correct syntax

2022-07-27 13:24 UTC, kashwy requested changes
the PR contains unnecessary files

2022-07-27 13:45 UTC, kashwy commented on src/Parsers/Kusto/KustoFunctions/KQLAggregationFunctions.cpp
> +    return true;
**make_list (Expr [, MaxSize])**

missed the optional arg

2022-07-27 13:47 UTC, kashwy commented on src/Parsers/Kusto/KustoFunctions/KQLAggregationFunctions.cpp
> +    } else
this is not a correct syntax

2022-07-27 20:36 UTC, SadiHassan commented on src/Parsers/Kusto/KustoFunctions/KQLAggregationFunctions.cpp
> +    } else
made changes and resubmitted.

2022-07-27 20:36 UTC, SadiHassan commented on src/Parsers/Kusto/KustoFunctions/KQLAggregationFunctions.cpp
> +    return directMapping(out,pos,"groupUniqArray");
made changes and resubmitted.

2022-07-27 20:36 UTC, SadiHassan commented on src/Parsers/Kusto/KustoFunctions/KQLAggregationFunctions.cpp
> +    return true;
made changes and resubmitted.

2022-07-27 20:36 UTC, SadiHassan commented on src/Parsers/Kusto/KustoFunctions/KQLAggregationFunctions.cpp
> +        out = "groupUniqArrayIf(" + max_size + " , " + expr + " , " + predicate+ " )";
made changes and resubmitted.

2022-07-27 20:36 UTC, SadiHassan commented on src/Parsers/Kusto/KustoFunctions/KQLAggregationFunctions.cpp
> +        out = "groupArrayIf(" + max_size + " , " + expr + " , " + predicate+ " )";
made changes and resubmitted.

2022-07-28 06:28 UTC, kashwy commented on src/Parsers/tests/gtest_Parser.cpp
> +            "SELECT indexOf([1, 5, 7], 5) - 1 AS t"
KQL array is a dynamic type, it's in the form **dynamic(["this", "is", "an", "example", "an", "example"])**

array_index_of(**[1, 5, 7]**, 5)  is not a correct dynamic

2022-07-28 06:35 UTC, kashwy commented on src/Parsers/Kusto/KustoFunctions/KQLDynamicFunctions.cpp
> -    out = res;
remove this line
String res = String(pos->begin,pos->end);

2022-07-28 06:36 UTC, kashwy commented on src/Parsers/Kusto/KustoFunctions/KQLDynamicFunctions.cpp
>      String res = String(pos->begin,pos->end);
remove this line:
String res = String(pos->begin,pos->end);

2022-07-28 12:23 UTC, kashwy commented on src/Parsers/Kusto/KustoFunctions/KQLDynamicFunctions.cpp
> +    ++pos; // move forward to pass ClosingSquareBracket
the above code only works for constant value array

2022-07-29 02:39 UTC, SadiHassan commented on src/Parsers/tests/gtest_Parser.cpp
> +            "SELECT indexOf([1, 5, 7], 5) - 1 AS t"
Yes, but we have not implemented `dynamic` type. That's why it's kept like this. Please correct me if I am wrong.

2022-07-29 02:43 UTC, SadiHassan commented on src/Parsers/Kusto/KustoFunctions/KQLDynamicFunctions.cpp
> -    out = res;
removed

2022-07-29 02:43 UTC, SadiHassan commented on src/Parsers/Kusto/KustoFunctions/KQLDynamicFunctions.cpp
>      String res = String(pos->begin,pos->end);
removed

2022-07-29 02:45 UTC, SadiHassan commented on src/Parsers/Kusto/KustoFunctions/KQLDynamicFunctions.cpp
> +    ++pos; // move forward to pass ClosingSquareBracket
Yes. I mentioned this in the description above: `supports only basic lookup. Doesn't support start index, length and occurrence.`

2022-07-29 03:31 UTC, kashwy commented on src/Parsers/tests/gtest_Parser.cpp
> +            "SELECT indexOf([1, 5, 7], 5) - 1 AS t"
the problem is, there is no type formated like **[1, 5, 7]** , this is not valid in KQL., nobody use **[1, 5, 7]** as an array in KQL

look at the example from Qradar:
```
// Build Mock Table
let Events = datatable (EventId:int, StartTime:int, EndTime:int,
        username: string,
        network_traffic___x_src_ipv4_value:dynamic,     // source_ip
        network_traffic___x_dst_ipv4_value:dynamic)     // dest_ip
    [1, 1, 2, "tom", dynamic(["204.76.105.32", "204.76.105.32"]), dynamic(["10.10.10.1", "10.10.10.2", "10.10.10.19", "10.10.10.85"]),
     2, 3, 4, "tom", dynamic(["204.76.105.32"]), dynamic(["10.10.10.1", "10.10.10.69"] ),
     3, 5, 6, "harry", dynamic(["204.12.10.1.3"]), dynamic(["204.12.10.1.3"])
    ];
Events
| project EventId, network_traffic___x_dst_ipv4_value, network_traffic___x_src_ipv4_value
| extend allips = set_union(network_traffic___x_src_ipv4_value, network_traffic___x_dst_ipv4_value)
| mv-expand allips
| summarize IpCount=count() by IP=tostring(allips)
| project IP, IpCount
```

use this link to validate KQL query : https://dataexplorer.azure.com/clusters/help/databases

suggestion:

1. add a enumerate  
    `dynamic`

  to **enum class KQLFunctionValue :**   in file  src/Parsers/Kusto/KustoFunctions/KQLFunctionFactory.h

2.   add a map:   
    `{"dynamic", KQLFunctionValue::dynamic}`
 to  **std::unordered_map <String,KQLFunctionValue> KQLFunctionFactory::kql_functions**  
 and   
```
        case KQLFunctionValue::dynamic:
            return std::make_unique<Dynamic>();
```
 to  **KQLFunctionFactory::get(String &kql_function)**
in file  src/Parsers/Kusto/KustoFunctions/KQLFunctionFactory.cpp
3. add class declare in  to  src/Parsers/Kusto/KustoFunctions/KQLDynamicFunctions.h
```
class Dynamic : public IParserKQLFunction
{ 
protected:
    const char * getName() const override { return "dynamic()"; }
    bool convertImpl(String & out,IParser::Pos & pos) override;
};
```
4.  add implementation of `class Dynamic `  to  src/Parsers/Kusto/KustoFunctions/KQLDynamicFunctions.cpp
```
bool Dynamic ::convertImpl(String &out,IParser::Pos &pos)
{
 
do some parsing here, right now., you only check array 
 if the input is an array, the return the array like:
      out = [ 1,2,4.... ]
else 
   throw exception ("not a valid dynamic ....")

}
```
5. in the  function ArrayIndexOf , use get `getConvertedArgument` to get the array 
6.

2022-07-29 03:46 UTC, kashwy commented on src/Parsers/Kusto/KustoFunctions/KQLDynamicFunctions.cpp
> +    ++pos; // move forward to pass ClosingSquareBracket
I have suggestion on the comments for the file gtest_Parser.cpp

and then :

```
String array;
    while(pos->type != TokenType::ClosingSquareBracket)
    {
        array += String(pos->begin,pos->end);
        ++pos;
    }

    if(pos->type == TokenType::ClosingSquareBracket)
        array += String(pos->begin,pos->end);
    else
        return false;
```

can be changed as 
```
String array = getConvertedArgument( fn_name, pos); 
```

this can work with
```
print array_index_of(dynamic([ "is", "an", "example", "an", "example"]),"an",2) 
print array_index_of(parse_json('[1, 2, 3, "four"]'),3)     <---- if parse_json implemented
```

same for the function aeeary_length , etc

2022-08-25 17:59 UTC, closed without merging