KQL_arithmetic
ClibMouse/ClickHouse pull request #220
Opened 2023-02-14 06:07 UTC by mcmajam

### Changelog category (leave one):
- New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
New KQL Arithmetic functions

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

2023-02-14 13:35 UTC, kashwy commented on src/Parsers/Kusto/KustoFunctions/KQLMathematicalFunctions.cpp
> +    out = "1/tan(" + getConvertedArgument(fn_name, pos) + ")";
possible divided by 0

2023-02-14 13:37 UTC, kashwy commented on src/Parsers/Kusto/KustoFunctions/KQLMathematicalFunctions.cpp
> +        expr = "rand() % " + arg;
possible divided by 0

0 need to be handled

2023-02-14 13:47 UTC, kashwy requested changes
divided by 0 need to be handled, and add this test case to functional test

2023-02-14 16:15 UTC, ltrk2 requested changes

2023-02-14 16:15 UTC, ltrk2 commented on src/Parsers/Kusto/KustoFunctions/KQLMathematicalFunctions.cpp
> +    String arg = getConvertedArgument(fn_name, pos);
```suggestion
    const auto arg = getArgument(fn_name, pos);
```

2023-02-14 16:15 UTC, ltrk2 commented on src/Parsers/Kusto/KustoFunctions/KQLMathematicalFunctions.cpp
> +    out = expr + "])";
You can use `IParserKQLFunction::getArguments` and then just iterate those (example: `StrCat::convertImpl`).

2023-02-14 18:23 UTC, mcmajam commented on src/Parsers/Kusto/KustoFunctions/KQLMathematicalFunctions.cpp
> +    out = "1/tan(" + getConvertedArgument(fn_name, pos) + ")";
Both KQL and CLickHouse with my changes will return infinite in this case. Behavior appears to be the same between the two.

2023-02-14 19:13 UTC, mcmajam commented on src/Parsers/Kusto/KustoFunctions/KQLMathematicalFunctions.cpp
> +        expr = "rand() % " + arg;
In order to match the behavior of KQL, when 0, it should be treated as randCanonical (between 0 and 1).

2023-02-14 19:39 UTC, kashwy commented on src/Parsers/Kusto/KustoFunctions/KQLMathematicalFunctions.cpp
> +    out = "1/tan(" + getConvertedArgument(fn_name, pos) + ")";
en, that's good, clikchouse already handled it

2023-02-15 02:51 UTC, kashwy approved these changes

2023-02-15 14:48 UTC, ltrk2 requested changes

2023-02-15 14:48 UTC, ltrk2 commented on src/Parsers/Kusto/KustoFunctions/KQLMathematicalFunctions.cpp
> +        throw Exception("max_of(): function expects [2..64] argument(s).", ErrorCodes::NUMBER_OF_ARGUMENTS_DOESNT_MATCH);
Perhaps you could implement bounds-checking in `getArguments` in a similar fashion to `IParserKQLFunction::directMapping` with the `const Interval & argument_count_interval` parameter.

You could then reuse this in `min_of`.

2023-02-15 14:48 UTC, ltrk2 commented on src/Parsers/Kusto/KustoFunctions/KQLMathematicalFunctions.cpp
> +    const auto arguments = getArguments(fn_name, pos, ArgumentState::Raw);
Beware that `ArgumentState::Raw` means the expression won't be translated from KQL to SQL. This is comes in handy when reusing another KQL function as a means of implementing another using `IParserKQLFunction::kqlCallToExpression`. Otherwise, you should stick with the default `ArgumentState::Parsed`.

2023-02-15 14:48 UTC, ltrk2 commented on src/Parsers/Kusto/KustoFunctions/KQLMathematicalFunctions.cpp
>  bool Rand::convertImpl(String & out, IParser::Pos & pos)
I think you might be missing a functional test case for this function.

2023-02-15 14:48 UTC, ltrk2 commented on src/Parsers/Kusto/KustoFunctions/KQLMathematicalFunctions.cpp
> +            + arg.value() + "), randCanonical())");
`arg` can potentially be anything ranging from column name or string literal to number. Here, you seem to have zoned in on just the number variant. It's best to treat it as if it could be an arbitrary expression.

The [`value_or`](https://en.cppreference.com/w/cpp/utility/optional/value_or) method of `std::optional` may come in handy.

2023-02-15 15:32 UTC, mcmajam commented on src/Parsers/Kusto/KustoFunctions/KQLMathematicalFunctions.cpp
>  bool Rand::convertImpl(String & out, IParser::Pos & pos)
It generates a random number. The value output will be different ever time, which is why I did not add a functional case.

2023-02-15 15:42 UTC, ltrk2 commented on src/Parsers/Kusto/KustoFunctions/KQLMathematicalFunctions.cpp
>  bool Rand::convertImpl(String & out, IParser::Pos & pos)
The output will be different, but its characteristics should be the same. For example:
```
print x = rand() | project x >= 0 and x <= 1;
print x = rand(1234) | project x >= 0 and x <= 1233;
```

2023-02-15 15:46 UTC, ltrk2 commented on src/Parsers/Kusto/KustoFunctions/KQLMathematicalFunctions.cpp
> +        expr = "rand() % " + arg;
It wouldn't impact functionality: the ternary operator is the combination of `:` and `?` instead of `if` and `else`.

2023-02-15 16:21 UTC, mcmajam commented on src/Parsers/Kusto/KustoFunctions/KQLMathematicalFunctions.cpp
> +            + arg.value() + "), randCanonical())");
The set of issues that have to be solved include expressions. As an example (1-1). Or in the future let a=1 -1. Or if the column value itself is 0 or a negative number etc... that can only be reasonable evaluated at run time and hence the multif and per your earlier suggestion moduloOrZero. Columns do work correctly. Quoted strings also correctly result in an error message.

2023-02-16 14:44 UTC, ltrk2 requested changes

2023-02-16 14:44 UTC, ltrk2 commented on src/Parsers/Kusto/KustoFunctions/IParserKQLFunction.cpp
> +    int argument_count = 0;
You don't need to keep count, `arguments.size()` (unsigned result) or `std::ssize(arguments)` (signed result) can do that for you.

2023-02-16 14:44 UTC, ltrk2 commented on src/Parsers/Kusto/ParserKQLOperators.cpp
>  };
You're removing changes introduced by others ([ParserKQLOperators.cpp](https://github.com/ClibMouse/ClickHouse/pull/220/files#diff-37dddbd00b7566af9d3e6bd76e4b41e8c470559181360742a43d63717d27706f), [2366_kql_operator_in_sql.reference](https://github.com/ClibMouse/ClickHouse/pull/220/files#diff-72f8e1e8f9184f607223a585e783a0ace8e4694860edf1f9e6b6ce9e2b5568ff), [02366_kql_operator_in_sql.sql](https://github.com/ClibMouse/ClickHouse/pull/220/files#diff-8b200e1b97ce3c35a0f124f6b94402e510dd59866ecc85944f562f01f30506e4)). Please make sure to undo these.

2023-02-16 20:43 UTC, ltrk2 approved these changes

2023-02-16 20:44 UTC, merged