Hash changes
ClibMouse/ClickHouse pull request #236
Opened 2023-02-28 20:53 UTC by mcmajam

### Changelog category (leave one):
- New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Add hash and hash_sha256 functions

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

2023-03-07 16:48 UTC, ltrk2 requested changes

2023-03-07 16:48 UTC, ltrk2 commented on src/Parsers/Kusto/KustoFunctions/KQLHashFunctions.h
> +class Hash_sha256 : public IParserKQLFunction
```suggestion
class HashSha256 : public IParserKQLFunction
```

2023-03-07 16:48 UTC, ltrk2 commented on src/Functions/FunctionsHashing.h
> +};
Wouldn't it be an option to use `reinterpret(xxHash64(..), 'Int64')` instead?

2023-03-07 17:49 UTC, ltrk2 requested changes

2023-03-07 17:49 UTC, ltrk2 commented on tests/queries/0_stateless/02366_kql_func_hash.sql
> +print ' -- hash --';
Please add test cases for some explicit types, like:
- `print hash(int(-1));`
- `print hash(long(-1));`

2023-03-14 22:20 UTC, ltrk2 requested changes

2023-03-14 22:20 UTC, ltrk2 commented on src/Parsers/Kusto/KQL_ReleaseNote.md
> +   `print hash_sha256('World')`
Please relocate these under the March XX section.

2023-03-14 22:20 UTC, ltrk2 commented on src/Functions/Kusto/kqlHash.cpp
> +#include <format>
Many of these includes are unnecessary. Please get rid of those that aren't needed.

2023-03-14 22:20 UTC, ltrk2 commented on src/Parsers/Kusto/KustoFunctions/KQLHashFunctions.cpp
> +    out = "hex(SHA256(" + kqlCallToExpression("tostring", {arg}, pos.max_depth) + "))";
Hashes are printed as lowercase in ADX and even the specification seems to indirectly imply this. A call to `lower` should suffice.

2023-03-14 22:20 UTC, ltrk2 commented on src/Parsers/Kusto/KustoFunctions/KQLHashFunctions.cpp
> +        mod ? ")) % " + mod.value() + ")" : ")");
Since you already have a native implementation you could move this in there for improved readability.

2023-03-14 22:20 UTC, ltrk2 commented on src/Functions/Kusto/kqlHash.cpp
> +    WhichDataType which(*argument.type);
You could put this in the initializer part of the conditional expression it's used in.
```
if (WhichDataType which(*argument.type); which.isInt8() || ...
```

2023-03-14 22:38 UTC, mcmajam commented on src/Functions/Kusto/kqlHash.cpp
> +    WhichDataType which(*argument.type);
For readability, given that the first conditional already contains 5 conditions and which is also used in the next else if condition.

2023-03-15 12:49 UTC, ltrk2 commented on src/Functions/Kusto/kqlHash.cpp
> +    WhichDataType which(*argument.type);
That's also fine.

2023-03-15 17:50 UTC, ltrk2 requested changes

2023-03-15 17:50 UTC, ltrk2 commented on src/Functions/Kusto/kqlHash.cpp
> +    if (arguments.size() == 0 || arguments.size() > 2)
```suggestion
    if (!arguments.empty() || arguments.size() > 2)
```

2023-03-15 17:50 UTC, ltrk2 commented on src/Functions/Kusto/kqlHash.cpp
> +    if (arguments.size() == 2 && !isUnsignedInteger(arguments[1].type))
```suggestion
    if (arguments.size() == 2 && !isNativeInteger(arguments[1].type))
```

Because it must also work for cases such as `print hash(-1, int(100))`.

2023-03-15 17:50 UTC, ltrk2 commented on src/Functions/Kusto/kqlHash.cpp
> +    const auto argument = arguments.front();
```suggestion
    const auto & argument = arguments.front();
```

2023-03-15 17:50 UTC, ltrk2 commented on src/Functions/Kusto/kqlHash.cpp
> +    const ColumnsWithTypeAndName hashargs{asArgument(tohash, "tohash")};
You could move this into the body of the conditional expression that follows.

2023-03-15 17:50 UTC, ltrk2 commented on src/Functions/Kusto/kqlHash.cpp
> +    if (arguments.size() == 2 && !isUnsignedInteger(arguments[1].type))
You'll need to go through all values of the column and check if any would fall below a value of `1`.

2023-03-16 12:45 UTC, ltrk2 approved these changes

2023-03-16 14:01 UTC, merged