Between not 2243
ClibMouse/ClickHouse pull request #238
Opened 2023-03-02 16:20 UTC by SadiHassan

### Changelog category (leave one):
- New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...
`between`, `!between` operator and `not()` function.

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

2023-03-03 04:59 UTC, kashwy commented on src/Parsers/TokenIterator.cpp
> +        {"not_between",
don't need `not_between` there are no  `not_between` and `!not_between`

2023-03-03 05:36 UTC, kashwy commented on src/Parsers/Kusto/ParserKQLOperators.cpp
> +            ++token_pos;
this parse has problems if there are additional conditions or multiple `between`

for example:

`Customers | project Age | where Age between (10 .. 12) or Age > 30 `

`Customers | project Age | where Age between (10 .. 12) or Age between (20 .. 30)`

2023-03-06 14:18 UTC, SadiHassan commented on src/Parsers/TokenIterator.cpp
> +        {"not_between",
Agreed, pushed changes, thanks!

2023-03-06 14:19 UTC, SadiHassan commented on src/Parsers/Kusto/ParserKQLOperators.cpp
> +            ++token_pos;
Agreed, pushed changes and it's working for additional conditions or multiple `between`s, thanks!

2023-03-07 06:37 UTC, kashwy reviewed
throw exception for these case:
```
 between ( .. )
 between (1 .. )
 between ( .. 2 )
```
otherwise there are strange SQLs generated for the following :
 Customers | where Age between (1 .. ) and Age <30
 Customers | where Age between ( ..  ) and Age <30

```
grumbles1.fyre.ibm.com :)  Customers | where Age between (1 .. ) and Age <30

SELECT *
FROM Customers
WHERE (Age >= 1) AND (Age <= and)

grumbles1.fyre.ibm.com :)  Customers | where Age between (.. ) and Age <30

SELECT *
FROM Customers
WHERE (Age >= AND) AND (Age <= (Age < 30))
```

2023-03-08 00:02 UTC, SadiHassan commented
Exception added. For input like,
`Customers | where Age between ( .. 2) and Age <30` or
`Customers | where Age between ( 1 .. ) and Age <30` or
`Customers | where Age between ( .. ) and Age <30`

Output: `Code: 62. DB::Exception: Syntax error, number of parameters do not match. (SYNTAX_ERROR)`

2023-03-08 05:53 UTC, kashwy commented on src/Parsers/tests/KQL/gtest_KQL_General.cpp
> +            "print not(false)",
put an alias like 
print res  = not(false)

2023-03-08 06:04 UTC, kashwy commented on src/Parsers/tests/KQL/gtest_KQL_operator_in_sql.cpp
>          }
found issue for the different datatype of left and right. 

ADX 

 between(): all arguments are expected to have the same type 'long'

 between(): expects scalar arguments with the same type as the source type: 'datetime'

etc.
while
```
grumbles1.fyre.ibm.com :) TableWithVariousDataTypes | project JoinDate | where JoinDate between (datetime('2020-01-01') .. 2)

SELECT JoinDate
FROM TableWithVariousDataTypes
WHERE (JoinDate >= kql_datetime('2020-01-01')) AND (JoinDate <= 2)

```

2023-03-09 13:48 UTC, SadiHassan commented on src/Parsers/tests/KQL/gtest_KQL_General.cpp
> +            "print not(false)",
Added.

2023-03-09 13:50 UTC, SadiHassan commented on src/Parsers/tests/KQL/gtest_KQL_operator_in_sql.cpp
>          }
Fixed. Throwing exception for type mismatch when first parameter is datetime and second param is not compatible with that. Need more work to throw exception for any kind of type mismatches. This is a To Do for now.

2023-03-09 16:20 UTC, ltrk2 requested changes

2023-03-09 16:20 UTC, ltrk2 commented on src/Parsers/Kusto/KustoFunctions/KQLGeneralFunctions.h
> +class Not : public IParserKQLFunction
Please format this file using `clang-format`.

2023-03-09 16:20 UTC, ltrk2 commented on src/Parsers/tests/KQL/gtest_KQL_operator_in_sql.cpp
> +            "SELECT *\nFROM\n(\n    SELECT JoinDate\n    FROM TableWithVariousDataTypes\n    WHERE (JoinDate >= kql_datetime('2020-06-30')) AND (JoinDate <= kql_datetime('2025-06-30'))\n)"
I think you could create a new test suite for these two operators, since they have nothing to do with the `kql` table function.

2023-03-09 16:20 UTC, ltrk2 commented on src/Parsers/tests/KQL/gtest_KQL_General.cpp
> +            "SELECT dictGetOrDefault('dictionary_table', 'value', '100', 'default')"
Please revert the changes in this particular row.

2023-03-09 16:40 UTC, ltrk2 requested changes

2023-03-09 16:40 UTC, ltrk2 commented on src/Parsers/Kusto/ParserKQLOperators.cpp
> +        }
I think it that most of this could be exchanged for something like this:
```
ParserToken dot_token(TokenType::Dot);
if (dot_token.ignore(pos) && dot_token.ignore(pos))
    do you thing after having matched two dots
```

2023-03-09 16:40 UTC, ltrk2 commented on src/Parsers/Kusto/ParserKQLOperators.cpp
> +                expr = expr_keep + " + " + expr;
I think we'd best avoid such textual manipulations for the sake of maintainability. I think it'd be best if we reused the implementation of [`between`](https://clickhouse.com/docs/en/sql-reference/operators/#between-function) already present in ClickHouse. The way you could do this is split the expression at the two dots, evaluate the two sides separately and then create a valid expression in CH SQL.

2023-03-09 21:35 UTC, kashwy commented on src/Parsers/Kusto/ParserKQLOperators.cpp
> +                expr = expr_keep + " + " + expr;
agree

2023-03-10 04:55 UTC, SadiHassan commented on src/Parsers/Kusto/ParserKQLOperators.cpp
> +                expr = expr_keep + " + " + expr;
Here CH `between` is reused only which is in line 242 (`new_expr += ch_op + " ";`). However, there might be a better way to handle input like `datetime .. timespan`, where the second parameter need to be converted to `datetime + timespan` which CH query will not do.  Let's have a chat and we can understand each other points better. Thanks!

2023-03-10 16:00 UTC, ltrk2 commented on src/Parsers/Kusto/ParserKQLOperators.cpp
> +                expr = expr_keep + " + " + expr;
In this case, you could substitute the string magic with a SQL expression that does this.

2023-03-18 00:54 UTC, SadiHassan commented
Closing as separate PRs were submitted for this.

2023-03-18 00:54 UTC, closed without merging