`gettype()` function 2395
ClibMouse/ClickHouse pull request #249
Opened 2023-03-09 15:47 UTC by SadiHassan

### Changelog category (leave one):
- New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

gettype() function implemented.

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

2023-03-09 16:07 UTC, ltrk2 requested changes

2023-03-09 16:07 UTC, ltrk2 commented on src/Parsers/Kusto/KustoFunctions/KQLGeneralFunctions.h
> +};
Please run `clang-format` on this file.

2023-03-09 16:07 UTC, ltrk2 commented on tests/queries/0_stateless/02366_kql_func_general.sql
> +Customers | print t = gettype(Age) | limit 1;
I think you could add a few more examples, with `print` or `range` instead of a tabular source.

2023-03-09 16:07 UTC, ltrk2 commented on src/Parsers/Kusto/KustoFunctions/KQLGeneralFunctions.cpp
> +    return directMapping(out, pos, "toTypeName");
A mapping needs to be performed on this in order to translate CH types to KQL. I implemented the machinery (`toString(toKQLDataType(..))`) for this in `src/Parsers/Kusto/KQLDataType.h` for `getschema`. Because of this, a native function has to be implemented instead of a simple direct mapping, because the mapping is only accessible from C++.

2023-03-09 21:27 UTC, kashwy commented on tests/queries/0_stateless/02366_kql_func_general.sql
> +Customers | print t = gettype(FirstName) | limit 1;
although this `print `is working in our implementation, but it's not correct ( this is a bug, and will be fixed), as `print `must be the first operator.

so use `project ` instead

2023-03-14 21:41 UTC, ltrk2 requested changes

2023-03-14 21:41 UTC, ltrk2 commented on src/Functions/Kusto/KqlGetType.cpp
> +    return DataTypeString().createColumnConst(input_rows_count, toString(toKQLDataType(which_data_type.idx)));
You can use `argument.type->getTypeId()` directly.

2023-03-14 21:41 UTC, ltrk2 commented on src/Functions/Kusto/KqlGetType.cpp
> +#include <format>
I think you can drop this include.

2023-03-15 00:24 UTC, SadiHassan commented on src/Parsers/Kusto/KustoFunctions/KQLGeneralFunctions.h
> +};
Code updated.

2023-03-15 00:24 UTC, SadiHassan commented on tests/queries/0_stateless/02366_kql_func_general.sql
> +Customers | print t = gettype(Age) | limit 1;
Code updated.

2023-03-15 00:24 UTC, SadiHassan commented on src/Parsers/Kusto/KustoFunctions/KQLGeneralFunctions.cpp
> +    return directMapping(out, pos, "toTypeName");
Code updated.

2023-03-15 00:24 UTC, SadiHassan commented on tests/queries/0_stateless/02366_kql_func_general.sql
> +Customers | print t = gettype(FirstName) | limit 1;
Code updated.

2023-03-15 00:25 UTC, SadiHassan commented on src/Functions/Kusto/KqlGetType.cpp
> +    return DataTypeString().createColumnConst(input_rows_count, toString(toKQLDataType(which_data_type.idx)));
Code updated.

2023-03-15 00:25 UTC, SadiHassan commented on src/Functions/Kusto/KqlGetType.cpp
> +#include <format>
Code updated.

2023-03-15 12:45 UTC, ltrk2 approved these changes

2023-03-15 12:57 UTC, kashwy approved these changes

2023-03-15 13:15 UTC, merged