make_string function
ClibMouse/ClickHouse pull request #255
Opened 2023-03-13 16:49 UTC by SadiHassan

### Changelog category (leave one):
- New Feature
### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- `make_string()` function implemented

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

2023-03-13 22:18 UTC, ltrk2 requested changes

2023-03-13 22:18 UTC, ltrk2 commented on src/Parsers/Kusto/KQL_ReleaseNote.md
The specification [says](https://learn.microsoft.com/en-us/azure/data-explorer/kusto/query/unicode-codepoints-to-string-function) that `make_string` is a deprecated alias for `unicode_codepoints_to_string`. @kashwy what do you think?

2023-03-13 22:18 UTC, ltrk2 commented on tests/queries/0_stateless/02366_kql_func_string.sql
1. What if you invoke it using an empty array, or no parameters?
2. You could also try far more interesting cases such as `print str = unicode_codepoints_to_string(range(48,57), range(65,90), range(97,122))`.
3. Since this is supposed to be Unicode, you could try some more exotic characters.

2023-03-13 22:18 UTC, ltrk2 commented on src/Parsers/Kusto/KustoFunctions/KQLStringFunctions.h
Please format this source file using `clang-format`.

2023-03-13 22:18 UTC, ltrk2 commented on src/Parsers/Kusto/KustoFunctions/KQLStringFunctions.cpp
> +    }
I'm afraid that this wouldn't work for arbitrary expressions, since you're referencing `dynamic` by text. My opinion is that a native function is required to handle the strange syntax that this function has.

2023-03-14 03:46 UTC, kashwy commented on src/Parsers/Kusto/KustoFunctions/KQLStringFunctions.cpp
> +    {
you don't need to check if the arg is number or dynamic outside the clickhouse.
for example 
```
print make_string(88, strlen('abcd')*25, dynamic([32,45,32,75,117,115,116,111]), range(48,55,1)) , in ADX  will get 
Xd - Kusto01234567
```

let see the args will be passed to ClickHouse:
`88, lengthUTF8('abcd')*25, [32,45,32,75,117,115,116,111], kql_range(48,55,1)`

let's check their type:
```
select toTypeName(88), toTypeName(lengthUTF8('abcd')*25), toTypeName([32,45,32,75,117,115,116,111]), toTypeName(kql_range(48,55,1))
┌─toTypeName(88)─┬─toTypeName(multiply(lengthUTF8('abcd'), 25))─┬─toTypeName([32, 45, 32, 75, 117, 115, 116, 111])─┬─toTypeName(kql_range(48, 55, 1))─┐
│ UInt8          │ UInt64                                       │ Array(UInt8)                                     │ Array(UInt8)                     │
└────────────────┴──────────────────────────────────────────────┴──────────────────────────────────────────────────┴──────────────────────────────────┘
```

so you can use the similar method as your code of line 403 to process each arg.
and note the arg  type accepted types by kql  are int, long, or  array of int or long , so if any one of the is not int (int8,16..., uint8,16.. ) or not an array of int,  just stop

2023-03-14 03:50 UTC, kashwy commented on src/Parsers/Kusto/KustoFunctions/KQLStringFunctions.cpp
> +    }
native function is not needed, check `toTypeName `may works

2023-03-14 03:57 UTC, kashwy commented on src/Parsers/Kusto/KQL_ReleaseNote.md
yes,  `unicode_codepoints_to_string `is not implemented

2023-03-19 22:29 UTC, SadiHassan commented on src/Parsers/Kusto/KustoFunctions/KQLStringFunctions.cpp
> +    {
If I do not check (at least) the arg is `Number` or not outside CH, it will break the `arrayMap`, right? For column type, I checked if it is `BareWord` or not (and it works for columns, I tested). The only challenge is how not to use string magic and replace `temp_arg != "dynamic"` with something else.

2023-03-21 23:37 UTC, SadiHassan commented on tests/queries/0_stateless/02366_kql_func_string.sql
tested with such inputs.

2023-03-21 23:38 UTC, SadiHassan commented on src/Parsers/Kusto/KustoFunctions/KQLStringFunctions.cpp
> +    }
native is implemented, to avoid string manipulation and to make it work for array datatype in columns.

2023-03-21 23:39 UTC, SadiHassan commented on src/Parsers/Kusto/KustoFunctions/KQLStringFunctions.cpp
> +                out += "char(" + getConvertedArgument(function_name, pos) + ")";
it works for column.

2023-03-22 01:36 UTC, kashwy commented on src/Functions/Kusto/kqlMakeString.cpp
> +            if (!(which.isUInt() || which.isInt() || which.isNothing()))
```suggestion
            if (!which.isUInt() && !which.isInt() && !which.isNothing()))
```

2023-03-22 01:40 UTC, kashwy commented on src/Functions/Kusto/kqlMakeString.cpp
> +            if (!(which.isUInt() || which.isInt() || which.isNothing()))
`which.isNothing()`  standfor  what?

2023-03-22 11:40 UTC, SadiHassan commented on src/Functions/Kusto/kqlMakeString.cpp
> +            if (!(which.isUInt() || which.isInt() || which.isNothing()))
This is for empty array. For example, `print t = make_string(dynamic([]), 80, 81)` should print `PQ` (ADX), but it was breaking in my implementation. For that reason, check `isNothing()` is necessary.

2023-03-22 14:24 UTC, ltrk2 requested changes

2023-03-22 14:24 UTC, ltrk2 commented on src/Parsers/Kusto/KQL_ReleaseNote.md
> +   `print str = make_string(75, 117, 115, 116, 111)`
Please move it under a new April XX, 2023 section of the release note.

2023-03-22 16:08 UTC, kashwy commented on src/Functions/Kusto/kqlMakeString.cpp
> +    auto func = FunctionFactory::instance().get("char", context);
only use **`char`**  may have limited functionalty
valid UTF range is  0 to 1,114,111 (from U+0000 to U+10FFFF).
in ADX if a value in that range is valid, if out of that range , an exception is thrown.
for a large value ( > 0xff ) try to find a way that can be split or used by CH function ,
also throw exception if out of range

2023-03-24 12:42 UTC, kashwy commented on src/Functions/Kusto/kqlMakeString.cpp
> +                if (temp < 0 || temp > 1114111)
this is a duplicated code, use a common function

2023-03-24 13:28 UTC, ltrk2 requested changes

2023-03-24 13:28 UTC, ltrk2 commented on src/Functions/Kusto/kqlMakeString.cpp
> +}
I don't think we should seek to reinvent the wheel. ClickHouse already has support for this in `src/Common/UTF8Helpers.h`. You need to use `DB::UTF8::convertCodePointToUTF8`, which does exactly this.

2023-03-24 13:59 UTC, ltrk2 requested changes

2023-03-24 13:59 UTC, ltrk2 commented on src/Functions/Kusto/kqlMakeString.cpp
> +                size_t len = arr_field.get<Array>().size();
```suggestion
                const auto len = arr_field.get<Array>().size();
```

2023-03-24 13:59 UTC, ltrk2 commented on src/Functions/Kusto/kqlMakeString.cpp
> +                    Field val = arr_field.get<Array>().at(k);
```suggestion
                    const auto & val = arr_field.get<Array>().at(k);
```

2023-03-24 13:59 UTC, ltrk2 commented on src/Functions/Kusto/kqlMakeString.cpp
> +                    long int temp = val.get<Int64>();
```suggestion
                    const auto code_point = val.get<Int64>();
```

2023-03-24 13:59 UTC, ltrk2 commented on src/Functions/Kusto/kqlMakeString.cpp
> +                long int temp = arguments[i].column->getInt(j);
```suggestion
                const auto code_point = arguments[i].column->getInt(j);
```

2023-03-24 13:59 UTC, ltrk2 commented on src/Functions/Kusto/kqlMakeString.cpp
> +        out_col->insert(row_str);
You could use `insertData` in order to avoid a copy.

2023-03-24 19:12 UTC, kashwy approved these changes

2023-03-24 19:20 UTC, merged