between function work in progress
ClibMouse/ClickHouse pull request #264
Opened 2023-03-16 22:52 UTC by SadiHassan

### Changelog category (leave one):
- New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

`between()` native function work in progress.

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

2023-03-17 15:22 UTC, kashwy commented on src/Parsers/Kusto/ParserKQLOperators.cpp
> +            if (token_pos->type == DB::TokenType::ClosingRoundBracket)
```suggestion
            if (token_pos->type == DB::TokenType::ClosingRoundBracket && bracket_count.isZero())
```

2023-03-17 15:53 UTC, kashwy commented on src/Parsers/Kusto/ParserKQLOperators.cpp
> +    new_expr += DB::IParserKQLFunction::getExpression(token_pos) + ",";
this is also need to parse until the pos of 2 dot
otherwise if an expression not started as a function will not work, like : 
`range x from 1 to 100 step 1 | where x between ((1+2) .. 20)`

but it works in ADX

2023-03-17 17:48 UTC, ltrk2 requested changes

2023-03-17 17:48 UTC, ltrk2 commented on tests/queries/0_stateless/02366_kql_operator_in_sql.sql
> +DROP TABLE IF EXISTS TableWithVariousDataTypes;
I think you could create a new test suite for these two operators, since they have nothing to do with the kql table function.

2023-03-17 17:48 UTC, ltrk2 commented on src/Parsers/tests/KQL/gtest_KQL_operator_in_sql.cpp
> +            "SELECT *\nFROM\n(\n    SELECT Age\n    FROM TableWithVariousDataTypes\n    WHERE kql_between(Age, 10, 12) OR kql_between(Age, 30, 50)\n)"
I think you could create a new test suite for these two operators, since they have nothing to do with the kql table function.

2023-03-17 17:48 UTC, ltrk2 commented on src/Functions/Kusto/kqlBetween.cpp
> +        throw Exception(ErrorCodes::NUMBER_OF_ARGUMENTS_DOESNT_MATCH, "Number of arguments in function {} doesn't match.", getName());
I don't think you need this, since `size_t getNumberOfArguments() const override { return 3; }` should take care of it.

2023-03-17 17:48 UTC, ltrk2 commented on src/Functions/Kusto/kqlBetween.cpp
> +        add_interval = true;
```suggestion
    const auto add_interval = WhichDataType(*comparable_arg2.type).isInterval();
```

2023-03-17 17:48 UTC, ltrk2 commented on src/Functions/Kusto/kqlBetween.cpp
> +    }
Since I define `kql_between(X, Y, Z)` as `greaterOrEquals(Y, X) and greaterOrEquals(X, Z)` I don't think you need to do all this. Let ClickHouse do the comparisons:
```
const ColumnsWithTypeAndName lhs_and_value{comparable_arg1, base_arg};
const auto lhs_and_value_compared = executeFunctionCall(context, "greaterOrEquals", lhs_and_value, input_rows_count);

const ColumnsWithTypeAndName value_and_rhs{base_arg, comparable_arg2};
const auto value_and_rhs_compared = executeFunctionCall(context, "greaterOrEquals", lhs_and_value, input_rows_count);

const ColumnsWithTypeAndName comparisons{asArgument(lhs_and_value_compared, "lhs_and_value_compared"), asArgument(value_and_rhs_compared, "value_and_rhs_compared")};
return executeFunctionCall(context, "and", comparisons, input_rows_count).first;

```

2023-03-18 00:31 UTC, SadiHassan commented on src/Functions/Kusto/kqlBetween.cpp
> +    }
Code updated, thanks!

2023-03-18 00:31 UTC, SadiHassan commented on src/Functions/Kusto/kqlBetween.cpp
> +        add_interval = true;
Code updated, thanks!

2023-03-18 00:32 UTC, SadiHassan commented on src/Functions/Kusto/kqlBetween.cpp
> +        throw Exception(ErrorCodes::NUMBER_OF_ARGUMENTS_DOESNT_MATCH, "Number of arguments in function {} doesn't match.", getName());
Code updated, thanks!

2023-03-18 00:32 UTC, SadiHassan commented on src/Parsers/tests/KQL/gtest_KQL_operator_in_sql.cpp
> +            "SELECT *\nFROM\n(\n    SELECT Age\n    FROM TableWithVariousDataTypes\n    WHERE kql_between(Age, 10, 12) OR kql_between(Age, 30, 50)\n)"
Code updated, thanks!

2023-03-18 00:32 UTC, SadiHassan commented on tests/queries/0_stateless/02366_kql_operator_in_sql.sql
> +DROP TABLE IF EXISTS TableWithVariousDataTypes;
Code updated, thanks!

2023-03-18 00:33 UTC, SadiHassan commented on src/Parsers/Kusto/ParserKQLOperators.cpp
> +    new_expr += DB::IParserKQLFunction::getExpression(token_pos) + ",";
Code updated, thanks!

2023-03-18 00:33 UTC, SadiHassan commented on src/Parsers/Kusto/ParserKQLOperators.cpp
> +            if (token_pos->type == DB::TokenType::ClosingRoundBracket)
Code updated, thanks!

2023-03-18 00:49 UTC, SadiHassan commented on src/Parsers/tests/KQL/gtest_KQL_operator_in_sql.cpp
> +            "SELECT *\nFROM\n(\n    SELECT Age\n    FROM TableWithVariousDataTypes\n    WHERE kql_between(Age, 10, 12) OR kql_between(Age, 30, 50)\n)"
Code updated, thanks!

2023-03-18 14:04 UTC, kashwy approved these changes

2023-03-18 14:05 UTC, kashwy approved these changes

2023-03-18 14:30 UTC, merged