KQL URL parse using x3
ClibMouse/ClickHouse pull request #272
Opened 2023-03-20 19:21 UTC by mcmajam

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Corrections to parse_url.

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

2023-03-21 12:48 UTC, ltrk2 requested changes

2023-03-21 12:48 UTC, ltrk2 commented on src/Functions/Kusto/kqlParseURL.cpp
> +FunctionKqlParseURL::executeImpl(const ColumnsWithTypeAndName & arguments, const DataTypePtr &, const size_t input_rows_count) const
We need to check that the argument is of type `String`. Perhaps you could have a few such examples of invocations with the wrong type as functional test cases.

2023-03-21 12:48 UTC, ltrk2 commented on src/Functions/Kusto/kqlParseURL.cpp
> +        std::string instr = arguments[0].column->getDataAt(i).toString();
```suggestion
        const auto in_str = arguments[0].column->getDataAt(i).toView();
```

2023-03-21 12:48 UTC, ltrk2 commented on src/Functions/Kusto/kqlParseURL.cpp
> +        outstr = std::format(
Since `std::format` already creates a string you can just go for:
```suggestion
        const auto out_str = std::format(
```

2023-03-21 12:48 UTC, ltrk2 commented on src/Functions/Kusto/kqlParseURL.cpp
> +        parse(instr.begin(), instr.end(), KQL_URL, url);
In order to check whether we've traversed the entire input string (ie. it conforms to the grammar) we need to pass copies of the input iterators and then compare them afterwards. You'll also need to take into account the return value of `parse`. Example: https://www.boost.org/doc/libs/develop/libs/spirit/doc/x3/html/spirit_x3/tutorials/complex___our_first_complex_parser.html

2023-03-21 13:38 UTC, mcmajam commented on src/Functions/Kusto/kqlParseURL.cpp
> +        parse(instr.begin(), instr.end(), KQL_URL, url);
I would not describe ADX as validating grammar. Any input string valid (even invalid URIs) still results in the below (This is also in the functional tests already.

print parse_url("");
{"Scheme":"","Host":"","Port":"","Path":"","Username":"","Password":"","Query Parameters":{},"Fragment":""}

I don't have a case to know what we should return on a parsing failure. Near as I can tell we should always return at minimum the above for any input string.

2023-03-21 14:32 UTC, ltrk2 commented on src/Functions/Kusto/kqlParseURL.cpp
> +const auto KQL_URL_HOST_def = lexeme[+(char_ - endhost)][set_host];
IPv6 is also a type of host, so you could merge that rule in the host and make it an alternative.

2023-03-21 14:47 UTC, ltrk2 commented on src/Functions/Kusto/kqlParseURL.cpp
> +        parse(instr.begin(), instr.end(), KQL_URL, url);
I'd kind of consider the case when it returns a dictionary with all empty fields as an implicit error - since no fields could be successfully determined. Whether or not we derive this from the execution of the grammar or the state of the intermediate object after parsing is a different story.

2023-03-22 05:50 UTC, mcmajam commented
I do not think supporting these is a good idea currently. 

ADX does very limited validation. Matching schema on a single colon in a string while trying to maintain the same matching lack of validation in ADX is going to lead to significant deviations in behavior between the two. Adding validation to make that work will also cause significant deviation in behavior. ADX appears to hinge all further parsing of URLs based on :// with no other validation of the schema.

Some of the ClickHouse URL parsing functions do not support this and require :// (domain, port and netloc which parsers incorrectly).

2023-03-30 22:08 UTC, ltrk2 requested changes

2023-03-31 17:59 UTC, ltrk2 requested changes

2023-03-31 17:59 UTC, ltrk2 commented on src/Functions/Kusto/kqlParseURL.cpp
> +const auto KQL_URL_AUTH_def = lexeme[(+(char_ - endauth)) >> colon >> (+(char_ - endauth) >> at)][set_auth];
```suggestion
const auto KQL_URL_AUTH_def = lexeme[+(char_ - endauth) >> colon >> (+(char_ - endauth) >> at)][set_auth];
```

2023-03-31 17:59 UTC, ltrk2 commented on src/Functions/Kusto/kqlParseURL.cpp
> +    +((question | ampersand) >> (+(char_ - equals) >> equals) >> (+(char_ - endarg))))][set_args];
I think it'd be better to have this capture just a single argument, and call it `KQL_URL_ARG_def` and down in `KQL_URL_def` you could have `*KQL_URL_ARG_def` instead of `-KQL_URL_ARGS_def`.

That way, you could capture it into a `std::vector<std::pair<std::string, std::string>>` and have a semantic action that uses `at_c<0>` as key and `at_c<1>` as value. It'd look something like this:
```
const auto add_arg = [](auto & ctx)
{
    const auto & key_and_value = _attr(ctx);
    _val(ctx).args.emplace_back(at_c<0>(key_and_value ), at_c<1>key_and_value ));
};
```

2023-04-03 12:27 UTC, ltrk2 approved these changes

2023-04-03 14:19 UTC, merged