isascii() function
ClibMouse/ClickHouse pull request #278
Opened 2023-03-29 17:28 UTC by SadiHassan

### Changelog category (leave one):
- New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

`isascii()` function.

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

2023-03-29 18:42 UTC, kashwy commented on src/Parsers/Kusto/KustoFunctions/KQLStringFunctions.cpp
> +    out = std::format("not arrayExists(x -> x < 0 or x > 127, arrayMap(x -> ascii(x), splitByRegexp('', assumeNotNull({}))))", arg);
is `splitByString  `less expensive  than `splitByRegexp' ?

2023-03-29 20:52 UTC, SadiHassan commented on src/Parsers/Kusto/KustoFunctions/KQLStringFunctions.cpp
> +    out = std::format("not arrayExists(x -> x < 0 or x > 127, arrayMap(x -> ascii(x), splitByRegexp('', assumeNotNull({}))))", arg);
Splitbystring didn't work. It requires a character to split by.

2023-03-30 00:49 UTC, SadiHassan commented on src/Parsers/Kusto/KustoFunctions/KQLStringFunctions.cpp
> +    out = std::format("not arrayExists(x -> x < 0 or x > 127, arrayMap(x -> ascii(x), splitByRegexp('', assumeNotNull({}))))", arg);
Sorry, I mixed up `splitByChar` with `splitByString`. Updated code with `splitByString` and it produces same result.

2023-03-31 18:36 UTC, ltrk2 requested changes

2023-03-31 18:36 UTC, ltrk2 commented on src/Parsers/Kusto/KustoFunctions/KQLStringFunctions.cpp
> +    String arg = getConvertedArgument(fn_name, pos);
```suggestion
    const auto arg = getArgument(fn_name, pos);
```

2023-03-31 20:32 UTC, kashwy approved these changes

2023-04-06 13:40 UTC, ltrk2 approved these changes

2023-04-06 15:06 UTC, merged