isutf8 function implemented
ClibMouse/ClickHouse pull request #279
Opened 2023-03-31 16:48 UTC by SadiHassan

### Changelog category (leave one):
- New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
 - `isutf8()` function

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

2023-03-31 18:41 UTC, ltrk2 requested changes

2023-03-31 18:41 UTC, ltrk2 commented on src/Parsers/Kusto/KQL_ReleaseNote.md
> +   *Note -* For hexa strings, need to append extra `0` for each (up to) three characters after `\x`. For example, for input `\xFFF`, need to add one `0` like `\x0FFF`. For input like `\xFFFF`, for th
This sounds very strange. Isn't there an issue with `isValidUTF8`? In theory, `0xFFFF` and `0x00FFFF` are supposed to be the same. Do you think you could check the way it's implemented?

2023-03-31 19:37 UTC, kashwy commented on src/Parsers/Kusto/KQL_ReleaseNote.md
> +   *Note -* For hexa strings, need to append extra `0` for each (up to) three characters after `\x`. For example, for input `\xFFF`, need to add one `0` like `\x0FFF`. For input like `\xFFFF`, for th
I guess because the `isValidUTF8 `in CH expect a buff of  `UInt8 *` 

 `isValidUTF8(const UInt8 * data, UInt64 len)`

should this be handled before calling  `isValidUTF8  `?

2023-04-03 13:50 UTC, ltrk2 commented on src/Parsers/Kusto/KQL_ReleaseNote.md
> +   *Note -* For hexa strings, need to append extra `0` for each (up to) three characters after `\x`. For example, for input `\xFFF`, need to add one `0` like `\x0FFF`. For input like `\xFFFF`, for th
It seems to work fine for `String` based on the code. 

I think that the ClickHouse implementation is actually perfectly correct, because `0xFFFF` doesn't seem like a valid UTF-8 sequence based on https://en.wikipedia.org/wiki/UTF-8#Encoding.

@SadiHassan I think you should try out a few actual UTF-8 sequences and if everything seems to be in order then I suggest we instead add a note to the documentation that it works differently from ADX, but it's correct.

2023-04-14 03:50 UTC, SadiHassan commented on src/Parsers/Kusto/KQL_ReleaseNote.md
> +   *Note -* For hexa strings, need to append extra `0` for each (up to) three characters after `\x`. For example, for input `\xFFF`, need to add one `0` like `\x0FFF`. For input like `\xFFFF`, for th
Right. Updated release note. I tested with some invalid inputs, CH is correct. There is a functional test file `00934_is_valid_utf8.sql` which has a lot of valid and invalid `utf8` examples. They match with other online tools, but ADX is always `true` for any cases!

2023-04-14 04:02 UTC, kashwy commented on tests/queries/0_stateless/02366_kql_func_string.reference
> +<<<<<<< HEAD
unsolved conflict

2023-04-14 04:06 UTC, SadiHassan commented on tests/queries/0_stateless/02366_kql_func_string.reference
> +<<<<<<< HEAD
sorry, updated.

2023-04-14 04:14 UTC, kashwy approved these changes

2023-04-14 04:15 UTC, merged