bug_fix_2520 (new_guid)
ClibMouse/ClickHouse pull request #280
Opened 2023-03-31 17:20 UTC by SadiHassan

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
`new_guid()` now throws exception if argument is passed.

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

2023-03-31 18:45 UTC, ltrk2 requested changes

2023-03-31 18:45 UTC, ltrk2 commented on tests/queries/0_stateless/02366_kql_func_string.sql
> +-- Code: 36. DB::Exception: Function new_guid expects 0 argument(s). (BAD_ARGUMENTS)
`print t = new_guid(1) -- { serverError NUMBER_OF_ARGUMENTS_DOESNT_MATCH }` (if `serverError doesn't work, try `clientError`)

2023-03-31 18:45 UTC, ltrk2 commented on src/Parsers/Kusto/KustoFunctions/KQLStringFunctions.cpp
>      return directMapping(out, pos, "generateUUIDv4");
This should do the trick:
```suggestion
    return directMapping(out, pos, "generateUUIDv4", {0, 0});
```

2023-03-31 19:00 UTC, SadiHassan commented on tests/queries/0_stateless/02366_kql_func_string.sql
> +-- Code: 36. DB::Exception: Function new_guid expects 0 argument(s). (BAD_ARGUMENTS)
code updated.

2023-03-31 19:39 UTC, kashwy approved these changes

2023-04-03 12:32 UTC, ltrk2 approved these changes

2023-04-03 14:11 UTC, merged