bug_fix_2512
ClibMouse/ClickHouse pull request #282
Opened 2023-04-03 15:34 UTC by SadiHassan

### Changelog category (leave one):

- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

`between()` is doing excess dots check now.

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

2023-04-03 18:23 UTC, ltrk2 requested changes

2023-04-03 18:23 UTC, ltrk2 commented on tests/queries/0_stateless/02366_kql_operators.sql
> +range x from 1 to 100 step 1 | where x between ( 8 + (4 * 2) / 8 + ((5 * 5 - 20) * 2)  20); -- {clientError 62. DB::Exception: Syntax error, number of dots do not match. (SYNTAX_ERROR)}
You don't need the entire error message, you can simply go with `-- { clientError SYNTAX_ERROR }`.

2023-04-03 20:42 UTC, SadiHassan commented on tests/queries/0_stateless/02366_kql_operators.sql
> +range x from 1 to 100 step 1 | where x between ( 8 + (4 * 2) / 8 + ((5 * 5 - 20) * 2)  20); -- {clientError 62. DB::Exception: Syntax error, number of dots do not match. (SYNTAX_ERROR)}
that's fine. I want to keep like this :)

2023-04-04 12:48 UTC, ltrk2 commented on tests/queries/0_stateless/02366_kql_operators.sql
> +range x from 1 to 100 step 1 | where x between ( 8 + (4 * 2) / 8 + ((5 * 5 - 20) * 2)  20); -- {clientError 62. DB::Exception: Syntax error, number of dots do not match. (SYNTAX_ERROR)}
Okay, no problem.

2023-04-06 04:05 UTC, SadiHassan commented on tests/queries/0_stateless/02366_kql_operators.sql
> +range x from 1 to 100 step 1 | where x between ( 8 + (4 * 2) / 8 + ((5 * 5 - 20) * 2)  20); -- {clientError 62. DB::Exception: Syntax error, number of dots do not match. (SYNTAX_ERROR)}
Never mind, it really looked messy. code updated :)

2023-04-06 13:46 UTC, ltrk2 approved these changes

2023-04-06 16:19 UTC, merged