Deliver bug fixes
ClibMouse/ClickHouse pull request #296
Opened 2023-04-27 12:55 UTC by mcmajam

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

2023-05-01 17:59 UTC, ltrk2 requested changes

2023-05-01 17:59 UTC, ltrk2 commented on src/Parsers/Kusto/KustoFunctions/KQLDateTimeFunctions.cpp
> +    }
I'd probably seek to implement this in the `date_add` function instead.

2023-05-01 17:59 UTC, ltrk2 commented on src/Parsers/Kusto/KustoFunctions/KQLDateTimeFunctions.cpp
> +    }
I'd probably seek to implement this in the `dateDiff` function instead.

2023-05-01 17:59 UTC, ltrk2 commented on src/Parsers/Kusto/KustoFunctions/KQLDateTimeFunctions.cpp
> +    String trail = "";
You could just use their default constructors and it'd amount to the same thing:
```suggestion
    String head;
    String trail;
```

2023-05-12 13:08 UTC, mcmajam commented on src/Parsers/Kusto/KustoFunctions/KQLDateTimeFunctions.cpp
> +    }
date diff in ClickHouse does not support fractional seconds. It is all based on seconds and the underlying transforms/timezone conversions.

2023-06-01 14:41 UTC, ltrk2 approved these changes

2023-06-07 11:09 UTC, merged