throw an exception if arg_max or arg_min have fewer than 2 arguments
ClibMouse/ClickHouse pull request #302
Opened 2023-05-03 01:54 UTC by bemitc

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

2023-05-03 06:12 UTC, kashwy commented on src/Parsers/Kusto/KustoFunctions/KQLAggregationFunctions.cpp
> +    if (arg_count < 2)
I think Laszlo has an implementation for validating the number of args, @ltrk2

2023-05-04 14:29 UTC, ltrk2 commented on src/Parsers/Kusto/KustoFunctions/KQLAggregationFunctions.cpp
> +    if (arg_count < 2)
@bemitc you can use `IParserKQLFunction::getArguments`.

2023-05-05 15:49 UTC, ltrk2 requested changes

2023-05-05 15:49 UTC, ltrk2 commented on src/Parsers/Kusto/KustoFunctions/KQLAggregationFunctions.cpp
> +    for (std::string expr_to_return : args | std::views::drop(1))
You could just go with:
```suggestion
    for (const auto& expr_to_return : args | std::views::drop(1))
```

2023-05-05 15:49 UTC, ltrk2 commented on src/Parsers/Kusto/KustoFunctions/KQLAggregationFunctions.cpp
> +        if (expr_to_return != args[0])
You could just affix this to `args | std::views::drop(1)` as `std::views::filter(..)`

2023-05-05 15:49 UTC, ltrk2 commented on src/Parsers/Kusto/KustoFunctions/KQLAggregationFunctions.cpp
>          }
I'd seek to apply the same modifications as with `arg_max`.

2023-05-17 18:32 UTC, ltrk2 approved these changes

2023-05-17 18:47 UTC, merged