Issue #2711 and general UUID improvement
ClibMouse/ClickHouse pull request #365
Opened 2023-06-28 14:35 UTC by kothiga

### Changelog category (leave one):
- Improvement
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Changed UUID internal representation to have proper byte continuity. Ensured backwards compatibility with serialization and hashing.

2023-06-28 15:12 UTC, ltrk2 requested changes

2023-06-28 15:12 UTC, ltrk2 commented on src/Functions/FunctionsHashing.h
> +                ToType hash = apply(key, reinterpret_cast<const char *>(&value), sizeof(value));
You could make this const (and even auto).

2023-06-28 15:12 UTC, ltrk2 commented on src/Functions/FunctionsHashing.h
> +            ToType hash = apply(key, reinterpret_cast<const char *>(&value), sizeof(value));
You could make this const (and even auto).

2023-06-28 20:39 UTC, kothiga commented on tests/queries/0_stateless/02769_uuid_format_serialization.sql
> +SELECT toUUID('417ddc5d-e556-4d27-95dd-a34d84e46a50') FORMAT RowBinary;
Addressed and improved the functional test.

2023-06-28 20:40 UTC, kothiga commented on src/IO/WriteHelpers.h
> +    writePODBinary(uuid, buf);
Good suggestion. Applied.

2023-06-28 20:40 UTC, kothiga commented on src/IO/ReadHelpers.h
> +    std::swap(uuid.items[0], uuid.items[1]);
Good suggestion. Applied.

2023-06-28 20:40 UTC, kothiga commented on src/Functions/FunctionsHashing.h
> +                ToType hash = apply(key, reinterpret_cast<const char *>(&value), sizeof(value));
Applied.

2023-06-28 20:40 UTC, kothiga commented on src/Functions/FunctionsHashing.h
> +            ToType hash = apply(key, reinterpret_cast<const char *>(&value), sizeof(value));
Applied.

2023-06-29 20:14 UTC, ltrk2 approved these changes

2023-06-29 20:18 UTC, kothiga commented
Fixed Issue #2711 and adjusted internal behavior of UUIDs

2023-06-29 20:19 UTC, merged