Fixed the wildcardToRegex method to return nullopt in case the the st…
ClibMouse/ClickHouse pull request #367
Opened 2023-06-29 18:51 UTC by bhavnajindal

…ring does not contain any wildcard

Related to Issue: https://github.ibm.com/ClickHouse/issue-repo/issues/2846

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Problem: The recent changes in PR# 359(https://github.com/ClibMouse/ClickHouse/pull/359) to method wildcardToRegex would convert every string into a valid Regex irrespective of whether it contained any wildcard character. This could potentially result in some performance issues as the wildcard columns are converted to subqueries whereas regular columns aren't.

Fix: The wildcardToRegex now has the return-type of std::optional<String>. It will only return a valid Regex if the staring contained any wildcard chars. Otherwise it returns {}

Tests:
All unit tests and functional tests now pass as expected.

2023-06-30 12:30 UTC, ltrk2 requested changes

2023-06-30 12:30 UTC, ltrk2 commented on src/Parsers/Kusto/ParserKQLProjectAway.cpp
> +        }
Since `regex_column` is convertible to bool, you can use it like so:
```
if (const auto regex_column = wildcardToRegex(column))
    wildcard_columns.push_back("'" + *regex_column + "'");
```

2023-06-30 15:21 UTC, bhavnajindal commented on src/Parsers/Kusto/Utilities.cpp
> +    return {};
Since the regex(std::string) and std::nullptr are of different types, the ternary operator throws an incompatible operand type error. Therefore, using the conditional operator could be better here.

2023-07-05 21:00 UTC, ltrk2 requested changes
Please make sure to format your changes using `clang-format`.

2023-07-05 21:09 UTC, ltrk2 approved these changes

2023-07-05 21:42 UTC, merged