[I1261]: printing datetime throws exceptions
ClibMouse/ClickHouse pull request #369
Opened 2023-07-06 18:34 UTC by bhavnajindal

Issue link: https://github.ibm.com/ClickHouse/issue-repo/issues/1261

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Added exception handling with a meaningful exception : `CANNOT_PARSE_DATETIME DateTime out of range`

Query
`print datetime('2299-11-08 15:55:55.123456Z');`

Output
`DB::Exception: DateTime out of range: While processing kql_datetime('2299-11-08 15:55:55.123456Z') AS print_0. (CANNOT_PARSE_DATETIME)`

2023-07-07 03:45 UTC, kashwy commented on src/IO/parseDateTimeBestEffort.cpp
this changes the behaviour of ClickHouse globally, that's not what we wanted.

We only change for KQL, for this issue, need to validate the datetime value inside the datetime function.
for example:  when  parsing `datetime('2299-11-08 15:55:55.123456Z')`  , validate if `'2299-11-08 15:55:55.123456Z'` is out of range. 
`'2299-11-08 15:55:55.123456Z' ` is a constant here, also check if it applicable to variable or column

2023-07-24 12:52 UTC, ltrk2 requested changes

2023-07-24 12:52 UTC, ltrk2 commented on src/Parsers/Kusto/KustoFunctions/KQLDataTypeFunctions.cpp
> +
Instead of relying on the input being a certain format, you could place this logic in the `kql_datetime` native function. Same thing goes for the conditional expression on line 61.

2023-07-28 16:00 UTC, ltrk2 requested changes

2023-07-28 16:00 UTC, ltrk2 commented on src/Functions/Kusto/kqlDateTime.cpp
> +    }
I think you get an exception if it goes out of range. Because of this, I'd probably look to wrap the conversion part in a try-catch block and rethrow something KQL-specific.

2023-08-18 15:35 UTC, ltrk2 approved these changes

2023-08-22 15:07 UTC, merged