I2527: Fixed NaN issue in variance functions
ClibMouse/ClickHouse pull request #379
Opened 2023-07-24 20:00 UTC by bhavnajindal

This PR contains fix for two issues:
Issue: https://github.ibm.com/ClickHouse/issue-repo/issues/2517
Issue: https://github.ibm.com/ClickHouse/issue-repo/issues/2518

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Variance
```
BUbu1.fyre.ibm.com :) range x from 1 to 5 step -1 | summarize variance(x);

SELECT IF(isNaN(varSamp(x) AS variance_18250), 0, variance_18250) AS variance_x
FROM
(
    SELECT *
    FROM
    (
        SELECT kql_range(1, 5, -1) AS x
    )
    ARRAY JOIN x
)

Query id: 30b50fe2-630a-4ba6-9bee-b32f6898d6f4

┌─variance_x─┐
│          0 │
└────────────┘

1 row in set. Elapsed: 0.048 sec. 
```

VarianceP
```
BUbu1.fyre.ibm.com :) range x from 1 to 5 step -1 | summarize variancep(x);

SELECT IF(isNaN(varPop(x) AS variance_48065), 0, variance_48065) AS variancep_x
FROM
(
    SELECT *
    FROM
    (
        SELECT kql_range(1, 5, -1) AS x
    )
    ARRAY JOIN x
)

Query id: 186770c0-dbf9-4a50-8c8f-5b5851cdb528

┌─variancep_x─┐
│           0 │
└─────────────┘

1 row in set. Elapsed: 0.054 sec. 

```

VarianceIf
```
BUbu1.fyre.ibm.com :) range x from 1 to 5 step -1 | summarize varianceif(x, abs(x) > 0);

SELECT IF(isNaN(varSampIf(x, abs(x) > 0) AS variance_35694), 0, variance_35694) AS varianceif_x
FROM
(
    SELECT *
    FROM
    (
        SELECT kql_range(1, 5, -1) AS x
    )
    ARRAY JOIN x
)

Query id: cb0d9d8f-c04d-4104-94f1-09f2b7b116af

┌─varianceif_x─┐
│            0 │
└──────────────┘

1 row in set. Elapsed: 0.073 sec. 
```

2023-07-31 19:57 UTC, ltrk2 requested changes

2023-07-31 19:57 UTC, ltrk2 commented on src/Parsers/Kusto/KustoFunctions/KQLAggregationFunctions.cpp
> +        "IF (isNaN(varSamp(if(toTypeName({0}) = 'Nullable(Nothing)', throwIf(toTypeName({0}) = 'Nullable(Nothing)', "
I think you'd be able to shorten this by using `throwIf(true, ..)` in case there wasn't a particular reason for duplicating the trigger condition for the exception.

2023-08-02 20:03 UTC, bhavnajindal commented on src/Parsers/Kusto/KustoFunctions/KQLAggregationFunctions.cpp
> +        "IF (isNaN(varSamp(if(toTypeName({0}) = 'Nullable(Nothing)', throwIf(toTypeName({0}) = 'Nullable(Nothing)', "
It was needed to duplicate the condition in `throwIf` because on using `throwIf(true, ..)` the exception is thrown even with the `If `computing to `false`. 

For example: In the below scenario x is not Null. Still the `throwIf ` throws an exception. Hence duplication is required.
```
SELECT IF(isNaN(varSamp(if(toTypeName(x) = 'Nullable(Nothing)', throwIf(true, 'summarize operator: Failed to resolve scalar expression named null'), x)) AS variance_18250), 0, variance_18250) AS variance_null
FROM
(
    SELECT *
    FROM
    (
        SELECT kql_range(1, 5, 1) AS x
    )
    ARRAY JOIN x
)

Query id: 9800d0b9-aadf-4f75-aa41-fd2ad772c635


0 rows in set. Elapsed: 0.233 sec. 

Received exception:
Code: 395. DB::Exception: summarize operator: Failed to resolve scalar expression named null: while executing 'FUNCTION throwIf(true :: 1, 'summarize operator: Failed to resolve scalar expression named null' :: 2) -> throwIf(true, 'summarize operator: Failed to resolve scalar expression named null') UInt8 : 3'. (FUNCTION_THROW_IF_VALUE_IS_NON_ZERO)
```

2023-08-18 15:52 UTC, ltrk2 approved these changes

2023-08-22 15:06 UTC, merged