Dynamic Array Functions
ClibMouse/ClickHouse pull request #38
Opened 2022-08-12 02:32 UTC by SadiHassan

### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...
**Dynamic Array Functions** 
- [array_sort_asc](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/arraysortascfunction)  
- [array_sort_desc](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/arraysortdescfunction)  

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

2022-08-19 01:35 UTC, kashwy commented on src/Parsers/Kusto/KustoFunctions/KQLDynamicFunctions.cpp
> +    String fn_name = getKQLFunctionName(pos);
there are several issues:
1. this implement only accept 2 arguments. actually it can has N args:
```
array_sort_asc(array1[, ..., argumentN])
array_sort_asc(array1[, ..., argumentN],nulls_last)
```
2. the result is not correct even if there 2 array as args,  (`using arraySort((x, y) -> y`  returns only one array. ) actually:
_Returns the **same number of arrays** as in the input, with the first array sorted in ascending order, and the remaining arrays ordered to match the reordered first array.
3. the condition maybe an expr  other than 'true' or 'false', let CH to check.
4. ArraySortAsc and ArraySortDesc have large block of same code. should use a common function.

2022-08-19 01:36 UTC, kashwy requested changes
there are several issues:
1. this implement only accept 2 arguments. actually it can has N args:
```
array_sort_asc(array1[, ..., argumentN])
array_sort_asc(array1[, ..., argumentN],nulls_last)
```
2. the result is not correct even if there 2 array as args,  (`using arraySort((x, y) -> y`  returns only one array. ) actually:
_Returns the **same number of arrays** as in the input, with the first array sorted in ascending order, and the remaining arrays ordered to match the reordered first array.
3. the condition maybe an expr  other than 'true' or 'false', let CH to check.
4. ArraySortAsc and ArraySortDesc have large block of same code. should use a common function.

2022-08-23 17:50 UTC, kashwy commented
here's a simple cases , 1 array, 1 bool expression, you can do the similar to other cases

```
bool ArraySortAsc::convertImpl(String &out,IParser::Pos &pos)
{
  String fn_name = getKQLFunctionName(pos);
    if (fn_name.empty())
        return false;
    
    String arr1 = getArgument(fn_name, pos);
    String nulls_last = getArgument(fn_name, pos);
    out =  std::format("if ({1}, arraySort({0}), concat( arraySlice(arraySort({0}) as as1, indexOf(as1, NULL) as len1 ), arraySlice( as1, 1, len1-1)))", arr1, nulls_last);

    return true;
}
```

here's the test result:

print t = array_sort_asc(dynamic([null, 'd', 'a', 'c', 'c']),true)

```
SELECT if(true, arraySort([NULL, 'd', 'a', 'c', 'c']), concat(arraySlice(arraySort([NULL, 'd', 'a', 'c', 'c']) AS as1, indexOf(as1, NULL) AS len1), arraySlice(as1, 1, len1 - 1))) AS t

┌─t──────────────────────┐
│ ['a','c','c','d',NULL] │
└────────────────────────┘
```

 print t = array_sort_asc(dynamic([null, 'd', 'a', 'c', 'c']),false)

```
SELECT if(false, arraySort([NULL, 'd', 'a', 'c', 'c']), concat(arraySlice(arraySort([NULL, 'd', 'a', 'c', 'c']) AS as1, indexOf(as1, NULL) AS len1), arraySlice(as1, 1, len1 - 1))) AS t

┌─t──────────────────────┐
│ [NULL,'a','c','c','d'] │
└────────────────────────┘
```
print t = array_sort_asc(dynamic([null, 'd', 'a', 'c', 'c']),1>0)

```
SELECT if(1 > 0, arraySort([NULL, 'd', 'a', 'c', 'c']), concat(arraySlice(arraySort([NULL, 'd', 'a', 'c', 'c']) AS as1, indexOf(as1, NULL) AS len1), arraySlice(as1, 1, len1 - 1))) AS t

┌─t──────────────────────┐
│ ['a','c','c','d',NULL] │
└────────────────────────┘
```

print t = array_sort_asc(dynamic([null, 'd', 'a', 'c', 'c']),1<0)
```
SELECT if(1 < 0, arraySort([NULL, 'd', 'a', 'c', 'c']), concat(arraySlice(arraySort([NULL, 'd', 'a', 'c', 'c']) AS as1, indexOf(as1, NULL) AS len1), arraySlice(as1, 1, len1 - 1))) AS t

┌─t──────────────────────┐
│ [NULL,'a','c','c','d'] │
└────────────────────────┘
```

2022-08-24 18:49 UTC, kashwy reviewed
do not delete  `src/Parsers/tests/gtest_dictionary_parser.cpp`
this file is not belong to us, we should not touch it

2022-08-24 19:11 UTC, SadiHassan commented
> do not delete `src/Parsers/tests/gtest_dictionary_parser.cpp`
> this file is not belong to us, we should not touch it

Added back. It was removed mistakenly.

2022-08-25 21:39 UTC, kashwy commented on src/Parsers/Kusto/KustoFunctions/IParserKQLFunction.cpp
> +                std::cout << "MALLIK expr here: " << expr << std::endl;
haha, this debug info

2022-08-25 21:40 UTC, kashwy commented on src/Parsers/Kusto/KustoFunctions/IParserKQLFunction.cpp
> +    if(pos->type != TokenType::ClosingRoundBracket  && String(pos->begin, pos->end) != "dynamic")
you can include check range

2022-08-25 21:46 UTC, kashwy commented on src/Parsers/Kusto/KustoFunctions/IParserKQLFunction.cpp
> +    }
this is special case, can it be in handled in general ? like:

1. get all args in a list , 
2. check if the last one is bool 
3. then process all args

2022-08-26 01:57 UTC, SadiHassan commented on src/Parsers/Kusto/KustoFunctions/IParserKQLFunction.cpp
> +                std::cout << "MALLIK expr here: " << expr << std::endl;
removed, lol :)

2022-08-26 02:00 UTC, SadiHassan commented on src/Parsers/Kusto/KustoFunctions/IParserKQLFunction.cpp
> +    if(pos->type != TokenType::ClosingRoundBracket  && String(pos->begin, pos->end) != "dynamic")
Sorry, didn't understand your comment. can you explain a bit?

2022-08-26 02:04 UTC, SadiHassan commented on src/Parsers/Kusto/KustoFunctions/IParserKQLFunction.cpp
> +    }
I did similar kind of thing as you suggested in cases where there are more than one array and we have boolean expression. In this case, it is obvious to have a boolean expression (condition of `if`), that's why it's handled like this.

2022-08-26 13:59 UTC, SadiHassan commented
Merging as @kashwy suggested and ready for testing by @larryluogit

2022-08-26 13:59 UTC, merged