Adding functional tests for IP Binary DateTime and more String functions
ClibMouse/ClickHouse pull request #40
Opened 2022-08-12 16:43 UTC by larryluogit

### Changelog category (leave one):
- Build/Testing/Packaging Improvement

2022-08-12 18:57 UTC, kashwy commented on tests/queries/0_stateless/02366_kql_func_string.sql
> +print trim_start("[^\w]+", strcat("-  ","Te st", "1", "// $"));
\w  need a escape

2022-08-12 19:04 UTC, kashwy commented on tests/queries/0_stateless/02366_kql_func_string.sql
> +print replace_regex(strcat('Number is ', '1'), 'is (\d+)', 'was: \1');
\d  need a escape?

2022-08-12 19:08 UTC, larryluogit commented on tests/queries/0_stateless/02366_kql_func_string.sql
> +print trim_start("[^\w]+", strcat("-  ","Te st", "1", "// $"));
are you sure? it works now without escape. And it works in Azure data explore.
adding escape makes no difference in this case.

2022-08-12 19:11 UTC, larryluogit commented on tests/queries/0_stateless/02366_kql_func_string.sql
> +print replace_regex(strcat('Number is ', '1'), 'is (\d+)', 'was: \1');
same as previous comments. it works without escape now.

2022-08-12 19:13 UTC, ltrk2 requested changes

2022-08-12 19:13 UTC, ltrk2 commented on tests/queries/0_stateless/02366_kql_func_ip.sql
> +print parse_ipv6_mask("255.255.255.255", 128) == '0000:0000:0000:0000:0000:ffff:ffff:ffff';
In these cases I believe that based on the specification only suffixes of 0-32 can be used in a meaningful way. This is reflected in the first example at https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/parse-ipv6-maskfunction.

2022-08-12 19:13 UTC, ltrk2 commented on tests/queries/0_stateless/02366_kql_func_ip.sql
> +-- print parse_ipv6_mask("::192.168.255.255/24", 128) == '0000:0000:0000:0000:0000:ffff:c0a8:ff00';
In these cases I believe that based on the specification only suffixes of 0-32 can be used in a meaningful way. This is reflected in the first example at https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/parse-ipv6-maskfunction.

2022-08-12 19:33 UTC, larryluogit commented on tests/queries/0_stateless/02366_kql_func_string.sql
> +print trim_start("[^\w]+", strcat("-  ","Te st", "1", "// $"));
I tested in Azure. The expression is correct. Adding escape return incorrect results in Azure data explore.

2022-08-12 20:31 UTC, ltrk2 commented on tests/queries/0_stateless/02366_kql_func_ip.sql
> +print parse_ipv6_mask("255.255.255.255", 128) == '0000:0000:0000:0000:0000:ffff:ffff:ffff';
I've just checked the Azure Data Explorer and these queries work there as you mentioned. This one, however: `print parse_ipv6_mask("127.0.0.1", 24)` does not produce the result stated at https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/parse-ipv6-maskfunction. In essence, I believe that their implementation is most likely non-compliant.

2022-08-13 03:45 UTC, kashwy commented on tests/queries/0_stateless/02366_kql_func_string.sql
> +print trim_start("[^\w]+", strcat("-  ","Te st", "1", "// $"));
I think Azure data explore using Verbatim string literals, like **@"[^\w]+"**   so now escape needed.

`print trim_end(@"[^\w]+", strcat("- ","Te st", "1", "// $"));  `    and 
`print trim_end("[^\\w]+", strcat("- ","Te st", "1", "// $"))`

get same result:
```
"print_0": - Te st1,
```
`print trim_end("[^\w]+", strcat("- ","Te st", "1", "// $")); `      get result:
```

Error 

 I could not parse that, sorry.

 clientRequestId: KustoWebV2;3744a207-6a93-40df-a36a-ccadb65e817a
```

`print trim_end(@"[^\\w]+", strcat("- ","Te st", "1", "// $")); `   get empty

2022-08-13 04:37 UTC, kashwy commented on tests/queries/0_stateless/02366_kql_func_string.sql
> +print trim_start("[^\w]+", strcat("-  ","Te st", "1", "// $"));
it all depends how a client tread the escape. in CH client, its good for both **"[^\\w]+"** and **"[^\w]+"**

so all good here

2022-08-15 21:21 UTC, HeenaBansal2009 approved these changes

2022-08-16 13:16 UTC, kashwy approved these changes

2022-08-16 13:42 UTC, SadiHassan approved these changes

2022-08-16 18:58 UTC, ltrk2 commented on tests/queries/0_stateless/02366_kql_func_ip.sql
> +print parse_ipv6_mask("255.255.255.255", 128) == '0000:0000:0000:0000:0000:ffff:ffff:ffff';
We discussed this with @larryluogit and came to the conclusion that the case I mentioned above should be disregarded and the function should work as if the mask was applied to the result of `parse_ipv6`.

2022-08-16 20:02 UTC, merged