Added the support for the replace_string function
ClibMouse/ClickHouse pull request #407
Opened 2024-01-19 19:36 UTC by MeenaRenganathan22

Replaces all string matches with a specified string.

### Changelog category (leave one):
- New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Added the support for the KQL replace_string function.

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

2024-01-21 05:39 UTC, kashwy commented on tests/queries/0_stateless/02366_kql_func_string.sql
> +print replace_string('Hello, number is 10, 20 and is 23, 24, is', 'is', 'was');
missing the result of added sql  and unit test

2024-01-21 05:39 UTC, kashwy requested changes
test

2024-01-21 05:41 UTC, kashwy requested changes
missing the result of added sql and unit test

2024-01-22 21:16 UTC, kashwy approved these changes

2024-02-28 21:39 UTC, josh-hildred approved these changes

2024-02-28 22:11 UTC, merged