String functions -phase 2 low priority defer ones
ClibMouse/ClickHouse pull request #74
Opened 2022-09-13 18:39 UTC by HeenaBansal2009

### Changelog category (leave one):
- New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Implements string functions phase 2 
extractjson()
parse_command_line()
parse_csv()
parse_json()
parse_version()
reverse()

https://zenhub.ibm.com/workspaces/clickhouse-project-61250df53aaf060db4e08052/issues/clickhouse/issue-repo/737

2022-09-15 16:00 UTC, kashwy commented on src/Parsers/Kusto/KustoFunctions/KQLFunctionFactory.cpp
> +        {"extract_json", KQLFunctionValue::extract_json},
extractjson is also valid:
https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/extractjsonfunction

2022-09-15 16:01 UTC, kashwy commented on src/Parsers/Kusto/KustoFunctions/KQLStringFunctions.cpp
>  }
remove extra lines

2022-09-15 16:03 UTC, kashwy commented on src/Parsers/Kusto/KustoFunctions/KQLStringFunctions.cpp
> +        }
is this being tested ? if with typeof, the token pos is not point the end of function, may get error

2022-09-15 16:03 UTC, kashwy commented on src/Parsers/Kusto/KustoFunctions/KQLStringFunctions.cpp
> +   // ++pos;
remove ,if not used

2022-09-15 16:04 UTC, kashwy commented on src/Parsers/Kusto/KustoFunctions/KQLStringFunctions.cpp
> +   // {
remove unused comments

2022-09-15 16:08 UTC, kashwy commented on src/Parsers/Kusto/KustoFunctions/KQLStringFunctions.cpp
> +    if ( arg.front() == '\"' || arg.front() == '\'' )
as discussed, the arg is ab expression, should not expecting there is  quoted symbol or dot.
we cannot parse it in c++, have to do it in CH

2022-09-15 16:11 UTC, kashwy commented on src/Parsers/Kusto/KustoFunctions/KQLStringFunctions.cpp
>  bool ParseVersion::convertImpl(String & out,IParser::Pos & pos)
this function need to parse version inside CH

2022-09-15 16:54 UTC, kashwy commented on src/Parsers/Kusto/KustoFunctions/KQLStringFunctions.cpp
> +    out = std::format("splitByChar(',' , substring({0} , 1 , position({0} ,'\n') -1 ))", csv_string);
how about there's no '\n' at the end of string ?

2022-09-27 15:44 UTC, HeenaBansal2009 commented on src/Parsers/Kusto/KustoFunctions/KQLStringFunctions.cpp
> +    if ( arg.front() == '\"' || arg.front() == '\'' )
I refactored the  implementation of ^ function.

2022-09-27 15:45 UTC, HeenaBansal2009 commented on src/Parsers/Kusto/KustoFunctions/KQLStringFunctions.cpp
> +    out = std::format("splitByChar(',' , substring({0} , 1 , position({0} ,'\n') -1 ))", csv_string);
I handled the scenario.Thanks !

2022-09-27 15:53 UTC, kashwy commented on src/Parsers/Kusto/KustoFunctions/KQLStringFunctions.cpp
> +    if (!datatype.empty())
the part of convention from old extract has some issues. please check new implemented version in this PR 
 https://github.com/ClibMouse/ClickHouse/pull/83

2022-09-27 16:00 UTC, kashwy commented on src/Parsers/tests/KQL/gtest_KQL_StringFunctions.cpp
> +            },
remove the extra space before }

2022-09-27 16:04 UTC, kashwy commented on src/Parsers/Kusto/KustoFunctions/KQLStringFunctions.cpp
> +        arg.erase( arg.size() - 1); // erase the last quote
arg.erase`( 0`, 1); // erase the first quote
        arg.erase`( a`rg.size() - 1); // erase the last quote

remove the space between '(' and '0', otherwise will get build error in OSS

2022-09-27 16:06 UTC, HeenaBansal2009 commented on src/Parsers/Kusto/KustoFunctions/KQLStringFunctions.cpp
> +        arg.erase( arg.size() - 1); // erase the last quote
@Yong, I ran the style-check script on this file and I didn't get the style check error on this line.

2022-09-27 16:08 UTC, kashwy commented on src/Parsers/tests/KQL/gtest_KQL_StringFunctions.cpp
>  })));
add functional tests for these cases

2022-09-27 16:09 UTC, kashwy commented on src/Parsers/Kusto/KustoFunctions/KQLStringFunctions.h
> +    const char * getName() const override { return "extract_json() , extractjson()"; }
"extract_json(`) , `extractjson()"   ->"extract_json(), extractjson()"

2022-09-27 16:11 UTC, kashwy commented on src/Parsers/Kusto/KustoFunctions/KQLStringFunctions.cpp
> +    out = std::format("if(position({0} ,'\n')::UInt8, (splitByChar(',', substring({0}, 1, position({0},'\n') -1))), (splitByChar(',', substring({0}, 1, length({0})))))" , csv_string);
`" , csv_string `- > `", csv_string`

2022-09-27 16:18 UTC, kashwy commented on src/Parsers/Kusto/KustoFunctions/KQLStringFunctions.cpp
> +    if (Poco::toLower(type) != "'windows'")
the arg  `parser_type ` only accept  lower case `windows ` only , use `toLower` will make it possible to use upper case, which is not correct.

2022-09-28 14:55 UTC, kashwy commented on src/Parsers/Kusto/KustoFunctions/KQLStringFunctions.cpp
> +                throw Exception(datatype + " is not a supported kusto data type for extract", ErrorCodes::UNKNOWN_TYPE);
not  `extract `, should be `extract_json`

2022-09-28 18:18 UTC, kashwy approved these changes

2022-09-30 14:39 UTC, ltrk2 requested changes

2022-09-30 14:39 UTC, ltrk2 commented on src/Parsers/Kusto/KustoFunctions/KQLStringFunctions.cpp
> +bool ParseJson::convertImpl(String & out, IParser::Pos & pos)
Since this particular function is supposed to return a `dynamic` type and JSON document may contain types we don't yet support (eg. property bag or mixed types) should we even be implementing this right now? I believe that the entire goal of this would be to parse JSON to dynamic, which we clearly can't do right now, can we? @kashwy what's your opinion on this?

2022-09-30 17:48 UTC, kashwy commented on src/Parsers/Kusto/KustoFunctions/KQLStringFunctions.cpp
> +        out = std::format("substring(arrayStringConcat( arrayMap(x ->leftPad(x, 8, '0') ,arrayMap(x ->empty(x) ? '0' : x, arrayResize(splitByChar('.', {}) , 4)))),8)", arg);
output is a decimal, can convert is string to decimal

2022-09-30 19:08 UTC, HeenaBansal2009 commented on src/Parsers/Kusto/KustoFunctions/KQLStringFunctions.cpp
> +        out = std::format("substring(arrayStringConcat( arrayMap(x ->leftPad(x, 8, '0') ,arrayMap(x ->empty(x) ? '0' : x, arrayResize(splitByChar('.', {}) , 4)))),8)", arg);
Thanks Yong ! I'll typecast the output string with Todecimal128OrNull()

2022-09-30 19:08 UTC, HeenaBansal2009 commented on src/Parsers/Kusto/KustoFunctions/KQLStringFunctions.cpp
> +bool ParseJson::convertImpl(String & out, IParser::Pos & pos)
Okay! I'll keep the implementation as is for now.

2022-10-05 18:48 UTC, merged