Fixed bugs
ClibMouse/ClickHouse pull request #75
Opened 2022-09-14 17:25 UTC by HeenaBansal2009

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
fixes bugs
https://zenhub.ibm.com/workspaces/clickhouse-project-61250df53aaf060db4e08052/issues/clickhouse/issue-repo/1197
https://zenhub.ibm.com/workspaces/clickhouse-project-61250df53aaf060db4e08052/issues/clickhouse/issue-repo/1150
https://zenhub.ibm.com/workspaces/clickhouse-project-61250df53aaf060db4e08052/issues/clickhouse/issue-repo/1110
https://zenhub.ibm.com/workspaces/clickhouse-project-61250df53aaf060db4e08052/issues/clickhouse/issue-repo/1112

2022-09-15 16:59 UTC, kashwy commented on src/Parsers/Kusto/KustoFunctions/KQLCastingFunctions.cpp
> +    /*
remove if not used

2022-09-20 05:43 UTC, kashwy commented on src/Parsers/Kusto/KustoFunctions/KQLCastingFunctions.cpp
> +            out = std::format("NULL");
no need to call  std::format

2022-09-20 05:51 UTC, kashwy reviewed
https://clickhouse.com/docs/en/development/style
7. Add spaces around binary operators (+, -, *, /, %, …) and the ternary operator ?:.

2022-09-20 05:54 UTC, kashwy commented on src/Parsers/Kusto/KustoFunctions/KQLCastingFunctions.cpp
>      if(pos->type == TokenType::StringLiteral || pos->type == TokenType::QuotedIdentifier)
6. In `if, for, while `and other expressions, a space is inserted in front of the opening bracket (as opposed to function calls).

2022-09-20 05:55 UTC, kashwy commented on src/Parsers/Kusto/KustoFunctions/KQLCastingFunctions.cpp
> +        if(res[exponential_pos +1] == '+' || res[exponential_pos +1] == '-' )
add space between "+1"

2022-09-20 05:57 UTC, kashwy commented on src/Parsers/Kusto/KustoFunctions/KQLCastingFunctions.cpp
> +    }
add space between "+1", "+2" 

exponential_pos+1,res.length()  ->  exponential_pos + 1, res.length()

2022-09-20 05:58 UTC, kashwy commented on src/Parsers/Kusto/KustoFunctions/KQLDataTypeFunctions.cpp
> +        out = std::format("toInt32({})",arg);
std::format("toInt32({})",arg);       ->std::format("toInt32({})", arg);

2022-09-20 05:59 UTC, kashwy commented on src/Parsers/Kusto/KustoFunctions/KQLDataTypeFunctions.cpp
> +        throw Exception("String is not parsed as double literal " , ErrorCodes::BAD_ARGUMENTS);
", ErrorCodes

2022-09-20 05:59 UTC, kashwy commented on src/Parsers/Kusto/KustoFunctions/KQLDataTypeFunctions.cpp
> +        out = std::format("toFloat64({})",arg);
toFloat64({})",arg);  -> toFloat64({})", arg);

2022-09-20 06:02 UTC, kashwy requested changes
we need to follow the OSS styles,
if we do not do it now, eventually we need to do  it when submit to OSS.

2022-09-20 06:03 UTC, kashwy commented on src/Parsers/Kusto/KustoFunctions/KQLDateTimeFunctions.cpp
> +        if(format.substr(format.length()- decimal -1,1) == last_delim)
add indent

2022-09-20 06:04 UTC, kashwy commented on src/Parsers/Kusto/KustoFunctions/KQLDateTimeFunctions.cpp
> +                std::cout <<"yes";
what is this?

2022-09-20 14:29 UTC, HeenaBansal2009 commented
> we need to follow the OSS styles,
> if we do not do it now, eventually we need to do it when submit to OSS.

Sure Yong, But this PR  is still under progress and not yet ready for review. I'll mark this as Draft.
There are few unit test cases failing due to the changes in timespan.

2022-09-23 18:39 UTC, kashwy commented on src/Parsers/Kusto/KustoFunctions/KQLDataTypeFunctions.cpp
> +        if(arg[exponential_pos +1] == '+' || arg[exponential_pos +1] == '-' )
spaces around both size of operators

2022-09-23 18:51 UTC, kashwy commented on src/Parsers/Kusto/KustoFunctions/KQLDateTimeFunctions.cpp
> +    bool is_hour_zero = std::stoi(datetime)%86400 >3600 ? false : true;
space around % >

2022-09-23 18:57 UTC, kashwy commented on src/Parsers/Kusto/KustoFunctions/KQLDateTimeFunctions.cpp
> +    if (decimal > 0 && formatspecifier.find('.')!=String::npos)
formatspecifier.find('.')!=String::npos)  -> formatspecifier.find('.') != String::npos)

2022-09-23 18:58 UTC, kashwy commented on src/Parsers/Kusto/KustoFunctions/KQLDateTimeFunctions.cpp
> +        out = std::format("formatDateTime( {0},'{1}')" ,datetime, formatspecifier);
"formatDateTime( {0},'{1}')" ,datetime, formatspecifier);  -> "formatDateTime( {0},'{1}')", datetime, formatspecifier);

2022-09-23 18:59 UTC, kashwy commented on src/Parsers/Kusto/KustoFunctions/KQLDateTimeFunctions.cpp
> +        format.erase(format.size() - 1 ); // erase the last quote
format.erase(format.size() - 1 );  -> format.erase(format.size() - 1);

2022-09-23 19:02 UTC, kashwy commented on src/Parsers/Kusto/KustoFunctions/KQLDateTimeFunctions.cpp
> +                out = std::format("concat(substring(toString(formatDateTime( toDateTime64({0},9,'UTC') ,'{1}')),1, length(toString(formatDateTime( toDateTime64({0},9,'UTC'),'{1}'))) - position( rever
datetime,formatspecifier,decimal,pad,last_delim,day_val   - > datetime, formatspecifier, decimal, pad,last_delim, day_val

and the line below

2022-09-23 19:04 UTC, kashwy commented on src/Parsers/Kusto/KustoFunctions/KQLDateTimeFunctions.cpp
> +        for (int i = arg_count;i < 7 ; ++i)
int i = arg_count;i < 7 ; ++i   -> int i = arg_count; i < 7; ++i

2022-09-23 19:05 UTC, kashwy commented on src/Parsers/Kusto/ParserKQLDateTypeTimespan.cpp
> +
this space has to be removed, otherwise won't pass the build when raise PR to OSS

2022-09-27 19:49 UTC, kashwy commented on src/Parsers/Kusto/KustoFunctions/KQLCastingFunctions.cpp
>      }
looks like the todecimal  only works for const expr out side of the CH.
consider this case:
```CREATE TABLE tbl
(    
    str String
)ENGINE = Memory;

INSERT INTO tbl VALUES ("123.561");
INSERT INTO tbl VALUES ("653.4");

tbl| project todecimal(str)
```
equivalent in KQL:

```
datatable (str :string )
['12356.66', '653.4']
|project todecimal(str)
```

2022-09-27 19:50 UTC, kashwy commented on src/Parsers/Kusto/KustoFunctions/KQLCastingFunctions.cpp
>          precision = 17;
where this value   (17) come from ?

2022-09-27 20:02 UTC, HeenaBansal2009 commented on src/Parsers/Kusto/KustoFunctions/KQLCastingFunctions.cpp
>      }
Sure Yong, I'll check this as a new issue. Since the previous issue was  raised for const values. 
Here is the new issue link:
https://zenhub.ibm.com/workspaces/clickhouse-project-61250df53aaf060db4e08052/issues/clickhouse/issue-repo/1413

2022-09-27 20:20 UTC, HeenaBansal2009 commented on src/Parsers/Kusto/KustoFunctions/KQLCastingFunctions.cpp
>          precision = 17;
Because KQL precision values are different in case of string argument and int argument

```
print todecimal(1234567876.345678909876543212345678987654234567234563)
print todecimal('1234567876.345678909876543212345678987654234567234563')
```

first outputs max 17 digit precision values

and the second one prints 34 digit precision ,

2022-09-27 20:23 UTC, kashwy approved these changes

2022-09-27 20:43 UTC, merged